#ifndef OPCODE_HPP
#define OPCODE_HPP

enum Opcodes
{
	// 1000以内为GS内部使用消息
	MSG_NULL_ACTION 			= 0,
	SMSG_TIMER_OCCUR,
	SMSG_GUID_REQUEST,
	SMSG_GUID_RETURN,
	SMSG_SCENE_INITED,					// 场景初始化完成
	SMSG_LOST_GATE_CONNECTION,			// gate失去连接
	SMSG_RECEIVE_SIGUSR_1,				// 收到用户信号1

	SCENE_XS2NS_REQ_ONLINE_SCENES,
	SCENE_NS2XS_ACK_ONLINE_SCENES,
	SCENE_NS2XS_NTF_NEW_SCENES,
	SCENE_XS2XS_REQ_CONNECTION,
	SCENE_XS2XS_ACK_CONNECTION,
	SCENE_XS2XS_NTF_SCENE_LOGOUT,

	// notify message between plugins
	NMSG_PLAYER_IS_ONLINE		= 100,	// 玩家上线广播
	NMSG_PLAYER_IS_OFFLINE,				// 玩家下线
	NMSG_PLAYER_JUMP_MAP,				// 玩家跳图, not used
	NMSG_PLAYER_IS_FIRST_ONLINE,		// 玩家第一次上线
	NMSG_ROLE_ADD,						// 招募伙伴广播
	NMSG_JOIN_SECT,						// 加入门派
	NMSG_PLAYER_LEVEL_UP,				// 升级广播
	NMSG_PLAYER_DEAD,					// 玩家死亡广播
	NMSG_PLAYER_SHORT_INIT,				// 玩家概要信息加载完成,不再使用，请使用NMSG_SHORT_INIT_FINISH
	NMSG_CREATE_ROLE,					// 创建Role实体之后的广播
	NMSG_FLUSH_ALL_ENTITY,				// 系统关闭，回写所有实体到数据库之前，通知消息
	NMSG_SHORT_FLUSH_FINISH,			// short flush finish， notify to player
	NMSG_SCENE_INITED,					// 场景初始化完成
	NMSG_PLAYER_ENTER_MAP,				// 跳图的时候，进入当前地图通知消息
	NMSG_PLAYER_LEAVE_MAP,				// 跳图的时候，离开当前地图通知消息
	NMSG_SHORT_INIT_FINISH,				// short init finish， guid : 0 , failed， guid : 1 , success
	NMSG_PVP_INIT_FINISH,				// pvp init finish， guid : 0 , failed， guid : 1 , success
	NMSG_DAY_CHANGE,					// 当天24点结束消息，针对每个玩家
	NMSG_PLAYER_ONLINE_DISPATCH_MSG,	// 同步客户端玩家信息之后
	NMSG_WEEK_CHANGE,					// 周日零点广播消息，针对每个玩家
	NMSG_PLAYER_VIP_LEVEL_UP,			// vip等级升级广播
	NMSG_DAY_CHANGE_SCENE,
	NMSG_WEEK_CHANGE_SCENE,
	NMSG_FIGHT_ENEMY,					// 通关enemy之后，广播消息
	NMSG_PRESTIGE_INCREASE,				// 声望增加广播
	NMSG_MONEY_INCREASE,
	NMSG_COIN_INCREASE,
	NMSG_ENERGY_INCREASE,
	NMSG_SENIORITY_INCREASE,
	NMSG_COMPLETE_ACHIEVEMENT_UNLOCK,	// 完成成就关联模块解锁广播
	NMSG_PLAYER_ONLINE_AGAIN,					// 玩家在线的情况下，异地上线
	NMSG_DAILYPOINTS_EVENT,					// 事件广播，为每日积分服务
	NMSG_ROLE_REMOVE,						// 伙伴离队广播
	NMSG_ROLE_REJOIN,						// 伙伴归队广播
	NMSG_PVP_FIGHT_START,					//pvp战前广播
	NMSG_PVP_FIGHT_END,						//pvp战后广播
    NMSG_TOWER_FLOOR,                       // 仗剑江湖达到N层了
	NMSG_REQUEST_QUALIFY_PLAYER_FIGHT_DATA_FINISH,	// 单服赛玩家数据加载完成
	NMSG_PLAYER_CHARGE,						// 玩家充值
	NMSG_COIN_COST,							// 元宝消费通知
	NMSG_UPDATE_FIGHT_POWER,				// 战力更新通知
	NMSG_MAKE_WORSHIP,						// 朝拜通知
	NMSG_RING_QUEST_ROUND_CMP,				// 环任务完成一轮通告
	NMSG_TASK_COMPLETE,						// 主线任务和支线任务完成通告
	NMSG_SYSTEM_UNLOCK,						// 功能模块解锁通知
	NMSG_INHERIT_SELECT,					// 传承，选择角色，返回角色相关信息
	NMSG_INHERIT_EXCUTE,					// 执行传承操作
	NMSG_DODGE_INFO,						// 轻功升级通知
	NMSG_BOSS_KILLER,						// 击杀世界boss通知
	NMSG_FIGHT_FAILED_GUIDE,				// 失败引导数据计算
	NMSG_EQUIPMENT_GROUP,					// 装备变更广播套装信息
	NMSG_RECRUIT_ALLROLE,					// 当存在新伙伴的时候，发送该通知
	NMSG_EQUIPMENT_ID_CHANGE,				// 广播伙伴装备id变更（包括:幻化，装卸装备）
	NMSG_TRIAL_FIRST_WIN,					// 明教试炼关卡首次胜利通知
	NMSG_USE_ITEM_NOTIFY,					// 使用特殊道具的广播, line广播也用这个消息
	NMSG_BIAOCHE_START,						// 镖车押送通知（开始押镖时通知）
	NMSG_STRENGTH_ONE_TIME,					// 强化通知
	NMSG_EDUCATION_ONE_TIME,				// 培养通知（每培养一次通知）
	NMSG_REQUEST_PAIR_PLAYER_FIGHT_DATA_FINISH,	// 2v2战斗数据加载完成
	NMSG_SWALLOW_PELLET,					// 吞噬丹药
    NMSG_TARGET_SHL,
    NMSG_TARGET_ARREST,
    NMSG_TARGET_TRAINING,
	NMSG_TARGET_HUANHUA,					// 幻化广播
	NMSG_TARGET_FUWEN,						// 符文升阶广播
	NMSG_TARGET_XIANGQIAN,					// 宝石镶嵌广播
	NMSG_TARGET_WIFE_CLR,					// 侠侣获取通知
	NMSG_TARGET_WIFE_LEVEL,					// 侠侣升级通知
	NMSG_TASK_ACCEPT,						// 接主线、支线任务通知
	NMSG_QQ_VIP_INFO,						// qq 黄钻信息通告

	RMSG_MSG_BASE				= 200,
	RMSG_PLAYER_VS_PLAYER,				// pvp
	RMSG_PLAYER_VS_ENEMY,				// pve
	RMSG_ROLE_BUFFER_ATTACH,				// 附加buffer
	RMSG_ROLE_BUFFER_EFFECT,				// buffer效果
	RMSG_ROLE_BUFFER_CLEAR,
	RMSG_ROLE_ADD,						// 招募
	RMSG_ROLE_REMOVE,					// 离队
	PMSG_UPDATE_REWARD,					// 更新奖励请求
	PMSG_ATTACH_SKILL,					// 附加被动技能
	PMSG_DETACH_SKILL,
	RMSG_ROLE_REJOIN,					// 归队
	PMSG_CREATE_ITEM,					// 创建物品
	PMSG_DELETE_ITEM,					// 删除物品
	PMSG_PICK_ITEM,						// 拾取物品
	PMSG_REMOVE_BAG_ITEM,				// 移除物品
	PMSG_DEDUCT_ITEM,					// 扣减物品数量
	PMSG_QUERY_ITEM,					// 查询物品数量
	PMSG_SECT_MEMBER_ONLINE,			// 请求门派在线人员列表
	PMSG_REDUCE_GOLD,					// 减扣金钱、元宝、阅历
	PMSG_CHAT_NOTIFY,					// 通告消息
	PMSG_REQUEST_BONUS,					// 计算奖励
	PMSG_PLAYER_JUMP_MAP,				// 请求跳图
	PMSG_REDUCE_ENERGY,					// 减扣体力
	PMSG_QUERY_ENERGY,					// 查询体力
	PMSG_REQUEST_ITEMS_FROM_MONSTER,	// 打赢怪物，计算怪物的任务物品掉落
	PMSG_PARTNER_BEEN_INVITED,			// 是否招募过相关伙伴查询
	PMSG_QUERY_BAG_BEFORE_PICK,			// 在拾取之前，查询物品背包格位
	PMSG_QUERY_ROLE_EMPTY_POS,			// 查询伙伴角色空位
	PMSG_QUERY_BAG_EMPTY_POS,			// 查询角色人物身上的空余背包格位
	PMSG_NOTIFY_CLIENT_MSG,				// 下发错误消息给客户端，可以是提示信息，也可以是错误信息，该信息仅供客户端展示
	PMSG_DELETE_ITEM_BY_ITEM_ID,		// 删除指定ID的所有物品
	PMSG_STHEN_RESET,					// 重置装备 id 及其强化属性
	PMSG_PLAYER_BUFFER_ATTACH,			// 请求添加player buffer接口
	PMSG_TASK_LIST_ON_NPC,				// npc模块请求任务模块，获取任务状态
	PMSG_REQUSET_FORM_LEVEL,			// 请求阵型等级
	PMSG_UPGRADE_FORM_LEVEL,			// 阵型升级，有心法模块请求阵型模块实现
	PMSG_ADD_ENERGY,					// 添加体力
	PMSG_REQUEST_BUFFER_FEATURE,		// 获取角色buffer状态标志
    PMSG_UPDATE_ATTRIBUTES,
	PMSG_UPDATE_PRESTIGE,				// 更新声望
	PMSG_UPDATE_ENEMY,					// 更新enemy血量，主要是boos的
	PMSG_ATTACK_BOSS,					// 攻击boss
	PMSG_CHANGE_CHAR_ABILITY,			// 修改角色被动技能
	PMSG_PLAYER_BUFFER_DETACH,			// 删除人物buffer
	PMSG_PLAYER_BATTLE_EFFECT,			// 人物buffer生效，一般战斗之前调用
	PMSG_PLAYER_BATTLE_INVALID,			// 人物buffer失效，一般战斗之后调用
	PMSG_UNLOCK_FUNCTION,				// 任务、关卡解锁功能
	PMSG_UNLOCK_VIP_FUNCTION,			// 解锁vip功能
	PMSG_QUERY_UNLOCK_VIP_FUNCTION,		// 查询vip功能是否已经解锁
	PMSG_QUERY_STOMACH_VALUE,			// 查询大胃值
	PMSG_ADD_STOMACH_VALUE,				// 增加大胃值
	PMSG_QUERY_UNLOCK_SYSTEM,			// 查询已经解锁功能
	PMSG_QUERY_ACHIEVE_UNLOCK,			// 查询成就是否解锁
	PMSG_QUERY_PARTNER_UNLOCK,			// 查询伙伴是否已经解锁
	PMSG_QUERY_SYSTEM_UNLOCK,			// 查询功能模块是否解锁
	PMSG_QUERY_ROLE_EDUCATE,			// 查询角色培养值
	PMSG_UPDATE_REVERENCE,				// 更新威望
	PMSG_REDUCE_REVERENCE,				// 减扣威望
	PMSG_CHAT_TO_OTHERS,				// 向聊天目标发送聊天内容
	PMSG_CHECK_CONTENT,					// 查询内容是否含禁词
	PMSG_PARTNER_INVITE,				// 请求招募
	PMSG_USE_DODGE_ITEM,				// 请求使用轻功卷轴物品
	PMSG_UPDATE_VIPEXP,					// 增加vip经验
	PMSG_REDUCE_DODGE_POINT,			// 请求减扣轻功点
	PMSG_ADD_DODGE_POINT,				// 请求增加轻功点
	PMSG_ADD_LUCKPOINTS,				// 添加机缘点数
	PMSG_WIFE_INFO_ROLE,				// 请求侠侣信息
	PMSG_REQUEST_QUALIFY_PLAYER_FIGHT_DATA,		// 单服赛请求加载玩家数据
	PMSG_CLEAR_QUALIFY_PLAYER_FIGHT_DATA,		// 单服赛玩家数据清理
	PMSG_MAIL_SEND,						// 邮件发送接口
	PMSG_MAZE_ADD_EXPLOREPOINT,			// 添加迷宫探索点
	PMSG_DODGE_INFO,					// 查询玩家当前轻功
	PMSG_EQUIPMENT_GROUP,				// 套装信息
	PMSG_RECRUIT_ALLROLE,				// 查询玩家当前招募的伙伴
	PMSG_EQUIPMENT_COLOR,
	PMSG_EQUIPMENT_CREATE,
	PMSG_QUERY_FIGHT_POWER,				// 战力查询
	PMSG_COMSUME_LUCK_POINTS,			// 消耗机缘点
    PMSG_RANKING_QUERY_GUILD,           // 查询帮会列表
    PMSG_RANKING_QUERY_PVP,             // 查询pvp列表
    PMSG_RANKING_QUERY_1VSN,            // 切磋
	PMSG_ASSEMBLE_FIGHT_PACKET,			// 组合战斗包
	PMSG_DEDUCT_ITEM_BY_GUID,			// 减扣指定guid物品数量
	PMSG_REDUCE_JIFEN,					// 扣除积分
	PMSG_QUERY_PLAYER_CHARGE,			// 查询玩家充值数
	PMSG_INHERIT_CHECK_EQUIPMENT,		// 检查伙伴身上武器是否满足传承要求
	PMSG_ADD_RUNES_STONE,				// 添加符文之石
	PMSG_ADD_RUNES_FIRE,				// 添加符文之火
	PMSG_ADD_JIFEN,						// 添加积分，即pk值
	PMSG_WIFE_MOODIFY_FATEPOINT,		// 缘分点
	PMSG_TARGET_QUERY_PELLET,			// 查询丹药数量
	PMSG_ADD_HIRE_CARD_ID,				// 添加伙伴卡牌
	PMSG_QUERY_TAVERN_HIRE_CARD_ID,		// 查询伙伴是否已经招募过
	PMSG_DODGE_UNLOCK_QUERY,			// 轻功类型是否解锁
	PMSG_DODGE_UNLOCK_EXEC,				// 轻功类型解锁
	PMSG_WIFE_HAS_WIFE,					// 查询是否有拥有某个侠侣
	PMSG_WIFE_GET_WIFE,					// 添加某个侠侣
    PMSG_TOWER_HISTORY_FLOOR,
	PMSG_ITEM_UNLOCK_LAW,				// 道具解锁心法

	PLMSG_LINE_REDUCE_GOLD		= 300,
	PLMSG_LINE_UPDATE_REWARD,
	PLMSG_TEAM_VS_ENEMY,
	PLMSG_GET_FRIEND,					// 请求好友列表
	PLMSG_PICK_UP,						// 请求LS物品拾取，默认部分拾取，放不下背包的物品则丢弃
	PLMSG_GUILD_BATTLING,				// line 帮会是否在战斗中
	PLMSG_GET_GUILD_MEMBER,				// 获取指定人所在帮会的所有成员guid
	PLMSG_CHECK_ENEMY,					// 检查是否为敌人
    PLMSG_ARREST_NOTIFY,
	PLMSG_GET_HERO_RANK_INFO,
    PLMSG_QUERY_RANKING,
	PLMSG_QUERY_VIP_NUMBER,
    PMSG_SHL_PAY_FRAG,                  // 消耗圣火令碎片
    PMSG_SHL_GET_FRAG,                  // 增加圣火令碎片
	PMSG_TARGET_QUERY_HUANHUA,
	PMSG_TARGET_QUERY_STRENGTH,
	PMSG_TARGET_QUERY_WIFE_LEVEL,
	PMSG_TARGET_QUERY_WIFE_CLR,
	PMSG_TARGET_QUERY_SHL,
	PMSG_TARGET_QUERY_DODGE,
	PMSG_TARGET_QUERY_PELLEP,
	PMSG_TARGET_QUERY_FUWEN,
	PMSG_TARGET_QUERY_ROLE,
	PMSG_TARGET_QUERY_XIANGQIAN,
	PMSG_TARGET_QUERY_TRAINING,
    PMSG_SOULPVE_PAY_FRAG,
    PMSG_SOULPVE_GET_FRAG,
	PMSG_QUERY_TASK_HISTORY,			//查询任务是否接收或者完成过
	PLMSG_REQUEST_ROBOT_BY_TYPE,		//查询指定类型机器人数量，目前只能line上插件调用
    PMSG_HORSE_USE,                     //双击使用马





	STOL_QUERY_MULTICOPY_FREE_TIMES = 350,	//proxy请求多人副本当天是否免费
	LTOS_QUERY_MULTICOPY_FREE_TIMES,		//副本返回当天是否免费以及是否能打
	LTOS_UPDATE_REWARD,
	STOL_UPDATE_REWARD,
	STOL_QUERY_FLOWER_FOR_GIVE,				// 送花金钱查询请求
	LTOS_QUERY_FLOWER_FOR_GIVE,
	STOL_MODIFY_BOSS_RANKING,				//修改boss排名到short模块
	STOL_QUERY_ESCORT_COST,
	LTOS_QUERY_ESCORT_COST,
	STOL_QUERY_PVP_COST,
	LTOS_QUERY_PVP_COST,
	STOL_ADD_BOSS_REWARD,
	STOL_TOWER_UPGRADE_NOTIFY,		//玩家推塔升级通知line scene更新排行榜
	LTOS_UPDATE_PLAYER_GUILD_NAME,	//更新玩家帮会名称
	LTOS_GUILDBATTLE_JOIN,			// 帮会战开始，可以进入地图，但不能战斗
	LTOS_GUILDBATTLE_START,			// 本轮帮会战正式开始（计时器驱动）
	LTOS_GUILDBATTLE_END,			// 本轮帮会战结束（计时器驱动）
	STOL_GUILDBATTLE_RESULT,		// scene 通知 line 帮会战结果
	LTOS_GUILDBATTLE_BROAD_TIME,	// 广播时间
	STOL_BATTLEGROUND_BUFF_GET,		// 获取阵营战的当前玩家的buff
	LTOS_BATTLEGROUND_BUFF_GET,		
	STOL_BATTLEGROUND_STAKE_INFO,	// 获取阵营战当前玩家的押注信息
	LTOS_BATTLEGROUND_STAKE_INFO,
	STOL_BATTLEGROUND_ATTACH_BUFF_NOTIFY,
	STOL_BATTLEGROUND_STAKE_NOTIFY,
	STOL_IN_SCENE_ALL_PLAYERS,				// 通知line在场景里的人，用于广播帮会成员职位
	LTOS_GET_GUILDBATTLE_REWARD,			// LINE 通知玩家领取奖励
	STOL_GET_GUILDBATTLE_REWARD_FAIL,		// 玩家通知 LINE，领取帮会战奖励失败
	STOL_QUERY_MAIL_ATTACH_COST,			//查询邮件附件消耗
	LTOS_QUERY_MAIL_ATTACH_COST,			//查询邮件附件消耗回复
	LTOS_DAILYPOINTS_EVENT_NOTIFY,			// 每日积分转场, 因为不支持line server调用
	SMSG_REQUEST_QUALIFY_PLAYER_FIGHT_DATA,	// 请求本服赛玩家数据
	SMSG_DELIVER_QUALIFY_PLAYER_FIGHT_DATA, // 传输本服赛玩家战斗相关数据
	SMSG_DELIVER_QUALIFY_PLAYER_FIGHT_DATA_START,	// 开始传输玩家数据
	SMSG_DELIVER_QUALIFY_PLAYER_FIGHT_DATA_FINISH,	// 玩家数据传输结束
	STOL_MAIL_SEND,
    STOL_ARREST_ROLES_UPDATE,               // 玩家在队的roles变动更新至line
    STOL_ARREST_ROLES_INFO,                 // 玩家在队的roles详细信息更新至line
    LTOS_ARREST_PRICE_QUERY,                // 返回scene, 价格
    STOL_ARREST_CONSUME_RESULT,             // 减扣成功..                    
	STOL_SYSTEM_UNLOCK_NOTIFY,
	LTOS_ARREST_UPDATE_ROLES,
	STOL_BOSS_INFO_SYNC,					//世界boss状态更新
	STOL_AMAH_DATA,							// 替身娃娃.每个需要设置替身娃娃的活动，在自己活动结束之后发送该消息
	STOL_REQUEST_PLAYER_DATA,
	LTOS_DELIVERY_PLAYER_DATA,
	LTOS_FAILED_REASON,
	STOL_OPEN_ACT_ADDTIME,							// sen to line. 添加了一个次数
	LTOS_OPEN_ACT_PRIZE_TIMES,						// line to sen. 次数更新消息
	LTOS_OPEN_ACT_STATE,							// 活动状态通知消息
    LMSG_RANKING_UPDATE_NOTIFY,			            // 排行榜变动通知
	LTOS_TITLE_CHANGE,								// 称号变更通知
	STOL_TITLE_ITEM_LOCK,							// 物品解锁称号信息
	STOL_SPLENDID_QUERY_COOL_TIME,
	LTOS_SPLENDID_QUERY_COOL_TIME,
	STOL_QUERY_SPLENDID_CANVASS,
	LTOS_QUERY_SPLENDID_CANVASS,
	LMSG_SPLENDID_TOP_FIVE,							// 五绝竞选结束，通知称号系统
	STOL_JIANZHONG_QUERY_BUY_COST,
	LTOS_JIANZHONG_QUERY_BUY_COST,
	LTOS_ADD_JIFEN,									//增加积分
	LTOS_SPLENDID_WORSHIP_GET_REWARD,
	STOL_SPLENDID_WORSHIP_GET_REWARD,
	STOL_PLAYER_GET_EXP,
	STOL_OPEN_ACT_PRIZE_PLAYER,								// 开服活动通知line第一个玩家领取了奖励
	LTOS_OPEN_ACT_PRIZE_PLAYER,								// 开服活动广播给sen.领取奖励的玩家
	LTOS_PICK_UP_ITEM,								// ls拾取物品，发送消息到scene，该消息为全部拾取消息
    STOL_ARREST_DAILY_PICK_ITEM,     
    STOL_ARREST_SHARED_PICK_ITEM, 
	STOL_PICK_UP_ITEM_OPENACT1_VIP,
	STOL_PICK_UP_ITEM_OPENACT1_NEWKING,
	STOL_TRIAL_RECORD,								// trial 试炼通知
	LTOS_TRIAL_RECORD,								// trial 试炼通知
	LTOS_INNER_REQUEST_LOGOFF,					// 玩家上线，数据还在其他地图，发送该消息让其下线
	STOL_USE_ITEM_NOTIFY,						//使用物品通告发送给line
	LTOS_BIAOCHE_START,							//押镖开始消息从line到scene
	ATOL_QUALIFYBATTLE_CHAMPION,				// 武林大会本服、跨服赛绝世榜冠军
	STOL_DELIVERY_PLAYER_DATA,
    STOL_TURNTABLE_UPDATE_COIN_POOL,            // 更新奖金池
    STOL_TURNTABLE_UPDATE_RECORD,               // 更新中奖记录
	STOL_TITLE_UNLOCK_TITLE,					// sen 解锁称号通知
	

	LMSG_REQUEST_PLAYER_FIGHT_DATA	= 450,	// 请求玩家战斗信息
	LMSG_PLAYER_FIGHT_PLAYER,				// 玩家战斗消息
	LMSG_GET_DATA_FROM_OTHER_SCENE_BACK,	// 获取其他场景玩家数据返回， 数据获取成功
	LMSG_GET_DATA_FROM_OTHER_SCENE_BACK_FAILED, // 获取其他场景玩家数据返回， 数据获取失败
	LMSG_PLAYER_FIRST_ONLINE,					// 玩家第一次上线，通知到line scene
	LMSG_PLAYER_UPGRADE_LEVEL,					// 玩家主角升级
	LMSG_PLAYER_IS_ONLINE,						// 玩家上线
	LMSG_PLAYER_IS_OFFLINE,						// 玩家下线
	LMSG_PLAYER_IS_JUMPMAP,						// 玩家跳图
	LMSG_PLAYER_JUMPMAP_READY,					// 跳图完成
	LMSG_STHEN_RATE,
	LMSG_WEEK_SYS_CARD,							// 向scene发送武林大坏蛋周卡片库
	LMSG_WEEK_CHANGE,							// ls发送week change消息到scene
	LMSG_DAY_CHANGE,							// ls发送day change消息到scene
	LMSG_REDUCE_GOLD,							// ls发送reduce gold 消息到scene
	LMSG_REDUCE_GOLD_RETURN,					// LMSG_REDUCE_GOLD消息返回
	LMSG_UPDATE_REWARD,							// ls发送update reward 消息到scene
	LMSG_UPDATE_REWARD_RETURN,					// 
	LMSG_PVP_FIGHT_REWARD,
	LMSG_PVP_DAY_REWARD,
	LMSG_PVP_WEEK_REWARD,
	LMSG_PVP_RESELECT_COST,
	LMSG_PVP_ADD_COUNT_COST,
	LMSG_PVP_RESET_COOLING_COST,
	LMSG_VIP_LEVLEUP,							// vip levelup
	LMSG_PLAYER_CHARGE,
	LMSG_PLAYER_CHARGE_CONFIRM,
	LMSG_WEEK_CHANGE_FOR_PLAYER,				// 玩家周切换，通知到LS
	LMSG_DAY_CHANGE_FOR_PLAYER,					// 玩家日切换，通知到LS
	LMSG_PLAYER_NOTIFY,							// 玩家通知
	LMSG_UNLOCK_MULTICOPY,						// 关卡解锁组队副本
	LMSG_GIVE_FLOWER_COST,						// 鲜花扣除金钱、元宝消费，回调操作码
	LMSG_GIVE_FLOWER_REWARD,					// 送鲜花成功，获得奖励，回调操作码
	LMSG_UPDATE_PLAYER_FIGHT_POWER,				// 更新玩家战力到LS
	LMSG_UPDATE_FLOWER_RANK,					// 更新玩家鲜花排名信息
	LMSG_PLAYER_ONLINE_AGAIN,					// 玩家在线的情况下，异地上线
	LMSG_PLAYER_ONLINE_DISPATCH_MSG,
	LMSG_PVP_BUY_TIMES_MAX_ACHIEVE_UNLOCK,		//竞技场购买挑战次数I级成就解锁
	LMSG_DAILYPOINTS_EVENT,						// 每日积分，LS同步到scene
	LMSG_RETURN_GUILD_CONSUME,					// 帮会相关操作失败，返回消耗 ls -> gs
	LMSG_UNLOCK_TOWN,							// 解锁玩家城镇
	LMSG_DAY_SYS_DODGE,
	LTOS_ACTIVITY_ADD,							// 活动添加
	LTOS_ACTIVITY_ADD_OVER,						// 活动添加完毕
	LTOS_ACTIVITY_REMOVE,						// 活动删除
	LTOS_ACTIVITY_START,						// 活动进入起始时间
	LTOS_ACTIVITY_END,							// 活动进入结束时间
	LTOS_ACTIVITY_PERIOD_START,					// 活动进入周期开始时间
	LTOS_ACTIVITY_PERIOD_END,					// 活动周期结束
	LTOS_ACTIVITY_LONGTIME,						// GS开启过程中巨大时间跳跃，要对在线玩家数据检测。
	// 临时添加的GM通知opercode.
	GMSG_ACTIVITY_ADD,
	SGMSG_ACTIVITY_ADD,
	GMSG_ACTIVITY_REMOVE,
	SGMSG_ACTIVITY_REMOVE,
	LTOS_SHORT_INIT_FINISH,
	LTOS_ACITIVTY_NEW_PERIOD,					// 活动进入新周期，未检测到周期结束（活动两个周期紧邻，一个周期结束之后，新的周期就开始了）
	LTOS_PVP_RANKING,							// 竞技场排名排名上升通知。
	LMSG_UPDATE_MODULE_FREE_TIME,
	LTOS_PVP_FIGHT,								// 竞技场战斗通知
	LTOS_QQINVITE_GEN_PRIZE,
	STOL_QQINVITE_RECV_PRIZE,


	NLMSG_PLAYER_IS_ONLINE			= 550,		// 玩家上线
	NLMSG_PLAYER_IS_OFFLINE,					// 玩家下线
	NLMSG_PLAYER_UPGRADE_LEVEL,					// 玩家主角升级
	NLMSG_PLAYER_JUMPMAP_READY,					// 玩家跳图完成，line s广播消息
	NLMSG_WEEK_CHANGE,							// 周日零点LS广播消息，广播完成之后，会通知到其他scene
	NLMSG_DAY_CHANGE,							// 每日零点LS广播消息，广播完成之后，会通知到其他scene
	NLMSG_VIP_LEVLEUP,							// vip levleup
	NLMSG_WEEK_CHANGE_FOR_PLAYER,				// LS广播，针对每个玩家，广播时间点周日零点和玩家上线
	NLMSG_DAY_CHANGE_FOR_PLAYER,				// LS广播，针对每个玩家，广播时间点每日零点和玩家上线
	NLMSG_PLAYER_IS_FIRST_ONLINE,				// 玩家第一次上线，LS通知
	NLMSG_PLAYER_ONLINE_AGAIN,					// 玩家在线的情况下，异地上线
	NLMSG_PLAYER_ONLINE_DISPATCH_MSG,
	NLMSG_UNLOCK_TOWN,							// 解锁玩家城镇
	NLMSG_SYSTEM_UNLOCK,
	NLMSG_ACTIVE_AMAH_PLAYER_GUID,
	NLMSG_ARENA_TOP,							// 每日竞技场前几通告
	NLMSG_RECIVE_FLOWER,						// 收到鲜花通知
	NLMSG_WEEKLY_FLOWER_RANK,					// 鲜花榜结算排名通知
	NLMSG_FRIST_GUILD_INFO,
    NLMSG_BATTLEGROUND_RESULT_NOTIFY,           // 大乱斗活动,战斗结果
    NLMSG_TOWER_RESULT_NOTIFY,                  // 仗剑江湖 推塔通知
	NLMSG_YINXIONG_TOP,							// 武林英雄大会通知接口,前三名

	LACB_BASE_MESSAGE				= 600,		// 

	SMSG_CROSS_SERVER_REGISTER		= 610,		// 连接跨服服务器注册消息
	SMSG_REQUEST_CROSS_PLAYER_FIGHT_DATA,		// 请求跨服赛玩家数据
	SMSG_CROSS_DELIVER_PLAYER_DATA_START,		// 开始传输玩家数据
	SMSG_CROSS_DELIVER_PLAYER_DATA_END,			// 
	SMSG_CROSS_DELIVER_PLAYER_DATA,
	PMSG_REQUEST_CROSS_PLAYER_FIGHT_DATA,
	PMSG_CLEAR_CROSS_PLAYER_FIGHT_DATA,
	NMSG_REQUEST_CROSS_PLAYER_FIGHT_DATA_FINISH,
	SMSG_CROSS_SERVER_DISCONNECT,
	NMSG_LINE_SERVER_CONNECTION,
	NMSG_LINE_SERVER_DISCONNECTION,
	SMSG_DELIVERY_CROSS_PLAYER_DATA_START,
	SMSG_DELIVERY_CROSS_PLAYER_DATA_END,
	SMSG_DELIVERY_CROSS_PLAYER_DATA,
	
	MMSG_MEMBER_REGISTER			= 700,
	MMSG_MEMBER_LOGIN,
	SMSG_MEMBER_LOGIN_RESPOND,
	SMSG_MEMBER_LOGIN_CONFIRM,
	MMSG_MEMBER_CHARGE,
	SMSG_MEMBER_CHARGE_CONFIRM,
	MMSG_QUERY_ROLE,
	SMSG_QUERY_ROLE_RETURN,
	SMSG_GATE_LOGIN_RESPOND,
	SMSG_MEMBER_REGISTER_SUCCESS,
	SMSG_MEMBER_REGISTER_FAILED,
	MMSG_QUERY_ONLINE_NUMBER,
	SMSG_QUERY_ONLINE_NUMBER,
	MMSG_MEMBER_GIVE_GIFT,
	SMSG_MEMBER_GIVE_GIFT,
	SMSG_REPORT_ONLINE_NUMBER,
	SMSG_MEMBER_LOGOFF,
    MMSG_QUERY_REGISTER_PLAYERS,
    SMSG_QUERY_REGISTER_PLAYERS,
    MMSG_QUERY_DAILY_TOP_PLAYERS,
    SMSG_QUERY_DAILY_TOP_PLAYERS,
    MMSG_QUERY_DAILY_AVERAGE_PLAYER,
    SMSG_QUERY_DAILY_AVERAGE_PLAYER,


	// 礼包系统注册消息
	SMSG_EXCHANGE_REGISTER			= 750,
	EMSG_EXCHANGE_REGISTER,
	SMSG_EXCHANGE_REMOTE_QUERY,
	EMSG_EXCHANGE_REMOTE_QUERY,
	SMSG_EXCHANGE_REMOTE_USED,
	EMSG_EXCHANGE_REMOTE_USED,


	IMSG_GS_STARTUP_REPORT			= 800,		// gs启动成功或者失败，报告消息，guid of package， 1 ： success ， 2：failed
	IMSG_GS_SHUTDOWN_REPORT,					// gs关闭时，保存完所有数据，报告消息，guid of package， 1 ： success ， 2：failed

	SMSG_DATA_RECORD				= 820,		// 日志记录消息码

	QMSG_START_OF_GS				= 830,		// 日志查询、GM工具消息码等 -----GAME SERVER-----
	QMSG_VALIDATION,							// 查询tools工具合法性验证
	GMSG_VALIDATION,							// 合法性验证回复
	QMSG_QUERY_DATA,
	GMSG_QUERY_ERROR,
	GMSG_QUERYSYS_REGISTER,
	QMSG_PUBLISH_ANNOUNCEMENT,
	GMSG_PUBLISH_ANNOUNCEMENT,
	QMSG_REMOVE_PUBLISH_ANNOUNCEMENT,
	GMSG_REMOVE_PUBLISH_ANNOUNCEMENT,
	QMSG_QUERY_PUBLISH_ANNOUNCEMENT,
	GMSG_QUERY_PUBLISH_ANNOUNCEMENT,

	QMSG_FORBID_SPEAKING,
	GMSG_FORBID_SPEAKING,
	QMSG_ALLOW_SPEAKING,
	GMSG_ALLOW_SPEAKING,
	QMSG_QUERY_SPEAKING,
	GMSG_QUERY_SPEAKING,
	QMSG_KICK_OFFLINE,
	GMSG_KICK_OFFLINE,
	QMSG_REQUEST_BENEFITS,
	GMSG_REQUEST_BENEFITS,
	QMSG_SEND_SYSTEM_MAIL,
	GMSG_SEND_SYSTEM_MAIL,
    QMSG_ADD_ACTIVITY,
    GMSG_ADD_ACTIVITY,
    QMSG_DEL_ACTIVITY,
    GMSG_DEL_ACTIVITY,
    QMSG_QUERY_ACTIVITY,
    GMSG_QUERY_ACTIVITY,

	// 武林大会
	QMSG_QUALIFYBATTLE_START,
	GMSG_QUALIFYBATTLE_START,
	QMSG_QUALIFYBATTLE_RESET,
	GMSG_QUALIFYBATTLE_RESET,	

	QMSG_QUERY_ONLINE_PLATFORM,
	GMSG_QUERY_ONLINE_PLATFORM,

    QMSG_SET_GS_LOG_LEVEL,
    GMSG_SET_GS_LOG_LEVEL,
    QMSG_GET_ONLINE_PLAYERS,
    GMSG_GET_ONLINE_PLAYERS,
    QMSG_CLEAN_GS_UNNORMAL_PLAYER,
    GMSG_CLEAN_UNNORMAL_PLAYER,  // 用于querysys返回
    QMSG_RESET_CLIENT_CONFIG,
    GMSG_RESET_CLIENT_CONFIG,

	QMSG_END_OF_GS,
	QMSG_START_OF_GATE	= 900,  //--------------GATE-----------------

	// ip
	QMSG_ALLOW_IP,
	GMSG_ALLOW_IP,
	QMSG_ALLOW_IP_REMOVE,
	GMSG_ALLOW_IP_REMOVE,
	QMSG_FORBID_IP,
	GMSG_FORBID_IP,
	QMSG_FORBID_IP_REMOVE,
	GMSG_FORBID_IP_REMOVE,

	QMSG_QUERY_IP_SET,
	GMSG_QUERY_IP_SET,

	// forbid account
	QMSG_FORBID_ACCOUNT,
	GMSG_FORBID_ACCOUNT,
	QMSG_FORBID_ACCOUNT_REMOVE,
	GMSG_FORBID_ACCOUNT_REMOVE,
	QMSG_FORBID_ACCOUNT_QUERY,
	GMSG_FORBID_ACCOUNT_QUERY,
    
    QMSG_CLEAN_GATE_UNNORMAL_PLAYER,
    QMSG_SET_GATE_LOG_LEVEL,
    GMSG_SET_GATE_LOG_LEVEL,

	QMSG_END_OF_GATE,

	// 数据库查询
    QMSG_START_OF_DATABASE = 930,   //----------DATABASE----------
	GMSG_QUERY_DATA_RECORD,
    GMSG_QUERY_CONCURRENT_PLAYERS,
    GMSG_PLAYER_INFO,
    GMSG_DAILY_TOP_PLAYERS,
    GMSG_DAILY_AVERAGE_PLAYERS,
	QMSG_END_OF_DATABASE,
	
		///登陆服消息 -start
	CMSG_CREATE_ACCOUNT = 1050,		    ///创建账户
	CMSG_LOGIN_ACCOUNT,					//验证账户
	CMSG_LOGIN_ACCOUNT_Req,				//验证账户请求
	CMSG_CHANGE_PW,				        //更改账户密码
	SMSG_ACCOUNT_RESULT,				//账户操作结果
	SMSG_LOGINREQUEST_REPLAY,		    //客服端登录请求返回
	SMSG_AUTH_SUCCESS,				    //账户验证成功
	GATEWAY_MSG_UPDATE,					///网关消息更新消息
	LOGIN_TOGATEWAY_AUTHMSG,			///登陆服发送验证信息给网关
	CMSG_SELECT_LINE,					// 暂不使用
	SMSG_LINE_STATES,					// 暂不使用
	GMSG_REPORT_ONLINE_PLAYERS,			///报告所有在线用户给login
	GMSG_REPORT_PLAYER_STATE,			///角色上线下线通知login
	GMSG_PLAYER_JUMP_MAP,				// 玩家跳图，gate通知target map
	
	GCMSG_REGISTER			= 1070,		/// GS连接Gate时注册Map ID消息	
	GMSG_CLIENT_CLOSE,					// 仅服务器使用
	GMSG_CLIENT_READ_ERROR,				// 仅服务器使用
	GMSG_CLIENT_WRITE_ERROR,			// 仅服务器使用
	GMSG_CLIENT_WOBBLE,					// 仅服务器使用
	GMSG_CLIENT_BEAT_TIMEOUT,			// 仅服务器使用
	GMSG_PLAYER_KICK_OFF,				// 踢玩家下线

	STOR_REPORT				= 1080,		//GS发送战报到战报服务器
	STOR_VERIFICATION,		//战报验证

	
	SMSG_ERROR					= 1090,  		/// 服务器向客户端描述一个错误


	SMSG_REQUEST_PLAYER_LIST		= 1100,		///服务器返回role list

	CMSG_CHECK_PLAYER_NAME,					///客户端检查角色名称消息
	SMSG_CHECK_PLAYER_NAME,					///服务器端返回角色名称检查通过消息
	CMSG_PLAYER_MAKE,						///客户端发送角色创建消息
	SMSG_PLAYER_MAKE,						///服务器返回角色创建消息
	CMSG_REQUEST_PLAYER_LIST,				///客户端发送请求角色列表消息
	CMSG_PLAYER_DELETE,						///客户端删除角色
	SMSG_PLAYER_DELETE,						///服务器端返回删除角色成功消息

	CMSG_LOOPBACK,						    /// 压力测试包
	CMSG_REQUEST_RANDOM_NAME,				// 创建角色随机名称
	SMSG_REQUEST_RANDOM_NAME,				// 创建角色随机名称返回


	// player list opcode
	CMSG_VALIATION_ACCOUNT 		= 1200,		///客户端连接gate发送的验证消息
	CMSG_PLAYER_BEAT,						// 客户端心跳包
	CMSG_GET_SERVER_TIME,					// 获取服务器时间
	SMSG_GET_SERVER_TIME,
		
	CMSG_PLAYER_ENTER_MAP 		= 1300,		/// 进入游戏
	SMSG_CREATE_SELF,						/// 人物进入游戏，服务器返回人物信息消息码
	SMSG_CREATE_OTHER,						/// 创建玩家周围其他人物
	SMSG_PLAYER_REMOVE,						/// 移除玩家周围其他人物
	
	CMSG_PLAYER_MOVE,						// 客户端移动消息
	SMSG_PLAYER_MOVE,						// 移动消息返回
	
	CMSG_PLAYER_LEAVE_MAP,					// 玩家下线消息
	SMSG_PLAYER_LEAVE_MAP,					// 玩家下线消息返回
	CMSG_PLAYER_JUMP_MAP,					// 客户端跳图消息
	SMSG_PLAYER_JUMP_MAP,					// 客户端跳图消息返回
	SMSG_CREATE_ROLE,						// 创建角色消息
	SMSG_PLAYER_UPGRADE_LEVEL,				// 暂不使用
	SMSG_ROLE_UPGRADE_LEVEL,				// 角色升级消息
	SMSG_ROLE_REMOVE,						// 删除角色消息
	SMSG_MONEY_UPDATE,						// 更新铜钱消息
	SMSG_UPDATE_ROLE_ATTR,					// 角色属性更新消息
	SMSG_UPDATE_ENERGY,						// 更新体力
	CMSG_REQUEST_ROLE_ATTR,					// 请求角色属性信息
	SMSG_REQUEST_ROLE_ATTR,					// 下发角色属性信息
	CMSG_JUMP_MAP_READY,					// 玩家跳图，客户端资源加载就绪，发送此消息给服务器，服务器下发其他玩家信息
	SMSG_UPDATE_PRESTIGE,					// 更新声望
	SMSG_UNLOCK_FUNCTION,					// 玩家上线，下发解锁列表
	SMSG_UPDATE_UNLOCK_FUNCTION,			// 玩家关卡、任务完成时，更新解锁列表
	SMSG_UPDATE_CHAR_ABILITY,				// 更新角色被动技能
	SMSG_DAY_CHANGE,						// 天切换通知，用于客户端清理天切换相关数据
	SMSG_UPDATE_FLOWER_RANK,				// 玩家鲜花榜排名变更，下发通知消息
	CMSG_LOOKUP_PLAYER,						// 查看玩家详细信息消息
	SMSG_LOOKUP_PLAYER,						
	SMSG_LOOKUP_CREATE_ROLE,
	SMSG_LOOKUP_CRATE_ITEM,
	SMSG_UPDATE_REVERENCE,					// 更新威望
	CMSG_SPECIAL_ACTION,					// 客户端特殊动作
	SMSG_SPECIAL_ACTION,
	SMSG_UPDATE_OTHER_GUILD_NAME,			// 更新其他玩家工会名称信息
	SMSG_GAIN_OFFLINE_EXP,
	CMSG_SPECIAL_ACTION_PERSON,
	SMSG_SPECIAL_ACTION_PERSON,
	CMSG_REQUEST_ROLE_ATTR_RANK,
	SMSG_REQUEST_ROLE_ATTR_RANK,
	SMSG_UPDATE_PLENTIFUL_ENERGY,
	CMSG_SELECT_INHERIT_ROLE,
	SMSG_SELECT_INHERIT_ROLE,
	CMSG_INHERIT_ROLE,
	SMSG_INHERIT_ROLE,
	SMSG_UPDATE_MODULE_FREE_TIME,
	SMSG_NOTIFY_LUCK_POINT,
	CMSG_SET_FOLLOW_ROLE,
	SMSG_SET_FOLLOW_ROLE,
	SMSG_UPDATE_FOLLOW_ROLE,
	SMSG_UPDATE_CURRENT_TITLE,
	SMSG_UPDATE_DOUBLEEXP_INFO,
	SMSG_LOOKUP_GUILD_NAME,
	SMSG_LOOKUP_DODGE,
	SMSG_HIRE_ZSLW,
	SMSG_UPDATE_SPECIAL_RIGHT,
	SMSG_SERVER_OPEN_TIME,
	SMSG_CLIENT_CONFIG,				//客户端配置字符串
	SMSG_UPDATE_YELLOW_VIP_LEVEL,	//黄钻等级更新

	CMSG_PLAYER_CHAT = 1400,
	SMSG_PLAYER_CHAR,
	SMSG_CHAT_NOTIFY,			// 通告消息
	SMSG_NOTIFY_CLIENT_MSG,
	SMSG_ERROR_DEBUG_MSG,
	SMSG_ERROR_MESSAGE,						// 错误提示，比如背包已满等
	SMSG_SYSTEM_NOTIFY,						// 系统通知
	STOL_CHAT_GUILD,			//转发给帮派聊天消息

	CMSG_FIGHT_ENEMY = 1500,
	CMSG_FIGHT_PLAYER,
	SMSG_ENEMY_REWARD,
	SMSG_MAP_REWARD,
	CMSG_SWEEP_STAGE,
	CMSG_SELECT_STAGE,
	SMSG_STAGE_REWARD,
	CMSG_OPEN_SWEEP,
	SMSG_OPEN_SWEEP,
	SMSG_UPDATE_STAGE_ATTACK_LIST,
	SMSG_DISPATCH_UNLOCK_TOWN,
	SMSG_UPDATE_BUY_ENERGY_TIME,
	CMSG_BUY_ENERGY,
	SMSG_BUY_ENERGY,
	CMSG_START_SWEEP,
	SMSG_START_SWEEP,
	SMSG_SWEEP_STAGE,
	SMSG_OFFLINE_SWEEP_INFO,
	CMSG_CANCEL_SWEEP,
	CMSG_CLEAR_TIRED_TIME,
	SMSG_CLEAR_TIRED_TIME,
	CMSG_SWEEP_ESSENCE,
	SMSG_SWEEP_ESSENCE,
	CMSG_RESET_ESSENCE,
	SMSG_RESET_ESSENCE,
	SMSG_UPDATE_SWEEP_COOL_TIME,

	SMSG_BATTLE_PLAYBACK = 1600,
	SMSG_ROLE_ALL_ATTR,

	SMSG_CREATE_PLAYER_FORM = 1700,
	CMSG_ADJUST_FORM,
	SMSG_ADJUST_FORM,
	CMSG_FORM_EXCHANGE_ROLE,
	SMSG_FORM_EXCHANGE_ROLE,
	SMSG_UPDATE_FORM_INFO,
	SMSG_FIGHT_FAILED_GUIDE,

	CMSG_PARTNER_RECRUIT	= 1800,
	SMSG_PARTNER_RECRUIT,

	CMSG_PARTNER_INVITE,
	SMSG_PARTNER_INVITE,

	CMSG_PARTNER_LEAVE,
	SMSG_PARTNER_LEAVE,
	SMSG_PARTNER_MEMBER_SLOT,
	CMSG_PARTNER_VIP_FUNC_UNLOCK,
	SMSG_PARTNER_VIP_FUNC_UNLOCK,

	CMSG_LAW_INFO			= 1900,
	SMSG_LAW_INFO,
	CMSG_LAW_UPGRADE,
	SMSG_LAW_UPGRADE,
	SMSG_LAW_COOLING_TIME,
	CMSG_RESET_LAW_COOLING,
	SMSG_RESET_LAW_COOLING,
	CMSG_LAW_VIP_FUN_UNLOCK,
	SMSG_LAW_VIP_FUN_UNLOCK,
	SMSG_LAW_NEW_UNLOCK,

	SMSG_CREATE_ITEM		= 2000,
	CMSG_ITEM_EQUIP,
	SMSG_ITEM_EQUIP,
	CMSG_ITEM_UNEQUIP, 
	SMSG_ITEM_UNEQUIP,
	CMSG_OPEN_BOX_ITEM,
	SMSG_OPEN_BOX_ITEM,

	CMSG_ITEM_MOVE			= 2100,
	SMSG_ITEM_MOVE,
	CMSG_NEATEN_BAG,
	SMSG_NEATEN_BAG,
	CMSG_BAG_ITEM_TRASH,
	SMSG_BAG_ITEM_TRASH,
	CMSG_UNLOCK_BAG,
	SMSG_UNLOCK_BAG,
	SMSG_UPDATE_ITEM_NUM,
	SMSG_SYNTH_EQUIP,
	CMSG_SYNTH_ITEM,
	CMSG_APPLY_ITEM,
	CMSG_UNPACK_BONUS,
	CMSG_PURCHASE_ITEM,         // obsolete
	CMSG_SYNTH_EQUIP,
    SMSG_UNPACK_BONUS,
    SMSG_SYNTH_ITEM,
	CMSG_STOMACH_ITEM,
	CMSG_EFFECTS_ITEM,
	CMSG_USE_ITEM,
	CMSG_ROLE_SCROLL_ITEM,
	SMSG_ROLE_SCROLL_ITEM,
	CMSG_FIREWORKS_ITEM,
	SMSG_FIREWORKS_ITEM,
	SMSG_STOMACH_ITEM,
	SMSG_UPDATE_VIP1_STOREHOUSE,
	SMSG_UPDATE_TIME_BAG,
	SMSG_UPDATE_TIME_UNLOCK_BAG,
	CMSG_DODGE_ITEM,
	SMSG_DODGE_ITEM,
	CMSG_EQUIPMENT_PUNCH,
	SMSG_EQUIPMENT_PUNCH,
	CMSG_GEM_SET,
	SMSG_GEM_SET,
	CMSG_GEM_GET,
	SMSG_GEM_GET,
	CMSG_GEM_SYNTH,
	SMSG_GEM_SYNTH,
	CMSG_GEM_FAST_SYNTH,
	SMSG_GEM_FAST_SYNTH,
	SMSG_SEND_EQUIPMENT,
	CMSG_GET_EQUIPMENT,
	SMSG_GET_EQUIPMENT,
	CMSG_GET_REWARD,
	SMSG_GET_REWARD,
	CMSG_USE_TITLE_ITEM,
	SMSG_USE_TITLE_ITEM,
	CMSG_USE_SPECIAL_ITEM,
	SMSG_USE_SPECIAL_ITEM,
	CMSG_DANYAO_SYNTH,
	SMSG_DANYAO_SYNTH,
	CMSG_ITEM_UNLOCK_LAW,
	SMSG_ITEM_UNLOCK_LAW,
	CMSG_ITEM_RESOLVE,
	SMSG_ITEM_RESOLVE,
	CMSG_MOUNT_ITEM,
	SMSG_MOUNT_ITEM,
    CMSG_ITEM_PET,
    SMSG_ITEM_PET,

	CMSG_SAVE_ATTR			= 2200,
	SMSG_SAVE_ATTR,
	CMSG_RESET_ATTR,
	SMSG_RESET_ATTR,
	CMSG_JOIN_SECT,
	SMSG_JOIN_SECT,
	CMSG_CANCLE_ATTR,
	SMSG_CANCLE_ATTR,
	CMSG_OPEN_PANEL_RESET_ATTR,
	SMSG_OPEN_PANEL_RESET_ATTR,

	SMSG_STHEN_ERROR		= 2300,
	SMSG_STHEN_QUEUE,
	CMSG_STHEN_FIRST_OPEN,
	SMSG_STHEN_FIRST_OPEN,
	CMSG_STHEN_EQUIP,
	SMSG_STHEN_EQUIP,
	CMSG_STHEN_UNLOCK,
	SMSG_STHEN_UNLOCK,
	CMSG_STHEN_PERCENT100,
	SMSG_STHEN_PERCENT100,
	CMSG_STHEN_ZEROCD,
	SMSG_STHEN_ZEROCD,
	CMSG_STHENO_HIRE,
	SMSG_STHENO_HIRE,
	CMSG_STHENO_FIRE,
	SMSG_STHENO_FIRE,
	CMSG_STHENO_REFRESH,
	SMSG_STHENO_REFRESH,
	CMSG_STHENO_MOVE,
	SMSG_STHENO_MOVE,
	SMSG_STHEN_SUCC_RATE,
	SMSG_STHENO_TIMEOUT,
	SMSG_STHEN_QUEUE_SINGLE,
	CMSG_COLOR_EQUIP,
	SMSG_COLOR_EQUIP,
    CMSG_STHEN_PERCENTTOP,
    SMSG_STHEN_PERCENTTOP,
    CMSG_STHEN_CD_HALF,
    SMSG_STHEN_CD_HALF,
    CMSG_STHEN_CD_NONE,
    SMSG_STHEN_CD_NONE,

	CMSG_ACCEPT_TASK	= 2400,
	SMSG_ACCEPT_TASK,
	CMSG_SUBMIT_TASK,
	SMSG_SUBMIT_TASK,
	SMSG_TASK_NUM_UPDATE,
	SMSG_TASK_STATE_UPDATE,
	CMSG_GIVEUP_TASK,
	SMSG_GIVEUP_TASK,
	SMSG_TASK_BRIEF_INFO,
	SMSG_CREATE_TASK,
	SMSG_DELETE_TASK,
	CMSG_TASK_CLIENT_AUTO_CMP,
	CMSG_REFRESH_DAILY_TASK,
	SMSG_REFRESH_DAILY_TASK,
	CMSG_UPGRADE_DAILY_TASK_LEVEL,
	SMSG_UPGRADE_DAILY_TASK_LEVEL,
	CMSG_DAILY_TASK_CMP_DIR,
	SMSG_DAILY_TASK_CMP_DIR,
	CMSG_RING_QUEST_OPEN,
	SMSG_RING_QUEST_OPEN,
	CMSG_RING_QUEST_GET_REWARD,
	SMSG_RING_QUEST_GET_REWARD,
	CMSG_RING_QUEST_REFRESH,
	SMSG_RING_QUEST_REFRESH,
	CMSG_RING_QUEST_RANDOM,
	SMSG_RING_QUEST_RANDOM,
	CMSG_RING_QUEST_CMP_DIR,
	SMSG_RING_QUEST_CMP_DIR,
	SMSG_RING_TIMES_FROM_ITEM,

	CMSG_OPEN_NPC		= 2500,
	SMSG_OPEN_NPC,

	CMSG_OPEN_EDUCATE	= 2600,
	SMSG_OPEN_EDUCATE,
	CMSG_RANDOM_EDUCATE,
	SMSG_RANDOM_EDUCATE,
	CMSG_SAVE_EDUCATE,
	SMSG_SAVE_EDUCATE,
	CMSG_CANCLE_EDUCATE,
	SMSG_CANCLE_EDUCATE,
	CMSG_REQUEST_COST_EDUCATE,
	SMSG_REQUEST_COST_EDUCATE,
	SMSG_EDUCATE_NOTIFY,

	CMSG_SHOP_OPEN		= 2700,
	SMSG_SHOP_OPEN,
	CMSG_ITEM_BUY,
	SMSG_ITEM_BUY,
	CMSG_ITEM_SELL,
	SMSG_ITEM_SELL,
	CMSG_ITEM_BUYBACK,
	SMSG_ITEM_BUYBACK,
	CMSG_BUYBACK_OPEN,
	SMSG_BUYBACK_OPEN,
    SMSG_SPECIALSHOP_OPEN,
	CMSG_SPECIALSHOP_BUY,
	SMSG_SPECIALSHOP_BUY,
    SMSG_SPECIALSHOP_DELIST,
    SMSG_SPECIALSHOP_ENLIST,
	CMSG_SPECIALSHOP_UNLOCK,
    SMSG_SPECIALSHOP_UNLOCK,
	SMSG_SHOP_ERROR,
	CMSG_LIMIT_ITEM_NUM,
	SMSG_LIMIT_ITEM_NUM,
	SMSG_PUSH_EXP_INFO,
	STOL_ITEM_BUY,
	LTOS_ITEM_BUY,
	STOL_ITEM_BUY_RESULT,
	CMSG_SEND_SHOP16_INFO,
	SMSG_SEND_SHOP16_INFO,

	CMSG_OPEN_PVP		= 2800,
	SMSG_OPEN_PVP,
	CMSG_PVP_FIGHT,
	SMSG_PVP_COOLING,
	CMSG_RESELECT_OPPO,
	SMSG_RESELECT_OPPO_COST,
	CMSG_ADD_COUNT_PVP,
	SMSG_ADD_COUNT_COST,
	SMSG_ADD_RECORD_PVP,
	SMSG_UPDATE_OPPO_PVP,
	SMSG_PVP_NOTIFY,
	CMSG_RESET_COOLING,
	SMSG_RESET_COOLING,
	CMSG_RANKING_LIST,
	SMSG_RANKING_LIST,
	SMSG_PVP_FREE_TIMES,
	SMSG_PVP_REWARD,
	SMSG_PVP_FIGHT_REWARD,
	SMSG_PVP_BRIEF_INFO,
	CMSG_PVP_GET_REWARD,
	SMSG_PVP_GET_REWARD,
	SMSG_PVP_CLEAR_COUNT_DOWN,
	SMSG_PVP_SELF_RANKING,

	SMSG_CHAKRA_ERROR	= 2900,
	CMSG_CHAKRA_OPEN,
	SMSG_CHAKRA_OPEN,
	CMSG_CHAKRO_RUN,
	SMSG_CHAKRO_RUN,
	CMSG_CHAKRO_ACT,
	SMSG_CHAKRO_ACT,
    CMSG_CHAKRE_SELL,
    SMSG_CHAKRE_SELL,
	CMSG_CHAKRE_MERGE,
	SMSG_CHAKRE_MERGE,
	CMSG_CHAKRE_AUTOMERGE,
	SMSG_CHAKRE_AUTOMERGE,
	CMSG_CHAKRP_ABSORB,
	SMSG_CHAKRP_ABSORB,
	CMSG_CHAKRS_UNLOCK,
	SMSG_CHAKRS_UNLOCK,
    CMSG_CHAKRE_STORE,
    SMSG_CHAKRE_STORE,
    CMSG_CHAKRE_TRASH,
    SMSG_CHAKRE_TRASH,

	CMSG_OPEN_WORSHIP	= 3000,
	SMSG_OPEN_WORSHIP,
	CMSG_MAKE_WORSHIP,
	SMSG_MAKE_WORSHIP,
	SMSG_UPDATE_WORSHIP_NUMBER,

	SMSG_OPEN_EGGS		= 3100,
	CMSG_OPEN_EGGS,
	CMSG_START_HIT_EGG,
	SMSG_START_HIT_EGG,
	CMSG_BUY_HAMMER,
	SMSG_BUY_HAMMER,
	CMSG_HIT_EGGS,
	SMSG_HIT_EGGS,
	CMSG_HIT_JOKER,
	SMSG_HIT_JOKER,
	CMSG_EGGS_WEEK_REWARD,
	SMSG_EGGS_WEEK_REWARD,
	SMSG_EGGS_WEEK_REWARD_NOTIFY,
	CMSG_EGGS_RESET_COOLING,
	SMSG_EGGS_RESET_COOLING,
	SMSG_EGGS_TIMES_FROM_ITEM,

	SMSG_CONDOR_COUNT	= 3200,	// obsolete
	SMSG_CONDOR_CLEAN,	// obsolete
	CMSG_CONDOR_SHOOT,
	SMSG_CONDOR_SHOOT,
	SMSG_CONDOR_AWARD,	// obsolete
	SMSG_CONDOR_NOTIFY,		
	CMSG_CONDOR_OPEN,
	SMSG_CONDOR_OPEN,
	CMSG_CONDOR_REQUEST_NEXT_ROUND,
	SMSG_CONDOR_REQUEST_NEXT_ROUND,
	CMSG_CONDOR_CLEAN_CD,
	SMSG_CONDOR_CLEAN_CD,
	CMSG_CONDOR_CHOOSE_WEAPON,
	SMSG_CONDOR_CHOOSE_WEAPON,
	
	
	SMSG_BOSS_APPEAR_STAGE = 3300,
	SMSG_BOSS_RESULT,
	CMSG_BOSS_JOIN,
	SMSG_BOSS_JOIN,
	SMSG_BOSS_CURRENT_HP,
	SMSG_BOSS_HURT_TOP,
	CMSG_BOSS_LEAVE,
	SMSG_BOSS_LEAVE,
	CMSG_BOSS_ENCOURAGE,
	SMSG_BOSS_ENCOURAGE,
	CMSG_BOSS_ATTACK,
	SMSG_BOSS_ATTACK,
	CMSG_BOSS_QUIK_REVIVE,
	SMSG_BOSS_QUIK_REVIVE,
	CMSG_BOSS_ATTACK_DIRECT,
	SMSG_BOSS_ATTACK_DIRECT,
	SMSG_BOSS_REWARD,
	SMSG_BOSS_KILL,
	CMSG_BOSS_GET_REWARD,
	SMSG_BOSS_GET_REWARD,
	SMSG_BOSS_KILLER_INFO,
	
	SMSG_ANSWER_COUNT = 3400,
	SMSG_ANSWER_CLEAN,
	CMSG_ANSWER_OPEN,
	SMSG_ANSWER_OPEN,
	CMSG_ANSWER_REQUEST,
	SMSG_ANSWER_REQUEST,
	CMSG_ANSWER_REPLY,
	SMSG_ANSWER_REPLY,
	SMSG_ANSWER_EVENT,
	CMSG_ANSWER_NEWDAY,
	SMSG_ANSWER_NEWDAY,
    SMSG_ANSWER_TIMEO,
    CMSG_ANSWER_POWER,
    SMSG_ANSWER_POWER,
    CMSG_ANSWER_STEP,
    SMSG_ANSWER_STEP,
    CMSG_ANSWER_VIP_UNLOCK,
    SMSG_ANSWER_VIP_UNLOCK,

	SMSG_ADDICTION_NOTIFY	= 3500,

	SMSG_HANG_UP_EXP	= 3600,

	CMSG_GIFT_STAT		= 3700,
	SMSG_GIFT_STAT,
	SMSG_GIFT_NEXT,
	SMSG_GIFT_TIME,
	CMSG_GIFT_TAKE,
	SMSG_GIFT_TAKE,
	SMSG_GIFT_UPDATE,

	SMSG_UPDATE_VIP_GIFT	= 3800,
	CMSG_TAKE_VIP_GIFT,
	SMSG_TAKE_VIP_GIFT,
	SMSG_UPDATE_EVERYDAY_VIP_GIFT,
	CMSG_TAKE_EVERYDAY_VIP_GIFT,
	SMSG_TAKE_EVERYDAY_VIP_GIFT,
	SMSG_VIP_LEVELUP,
	SMSG_OBTAIN_REWARDS,
	SMSG_UPDATE_FIRST_CHARGE_GIFT,
	CMSG_OBTAIN_FIRST_CHARGE_GIFT,
	SMSG_OBTAIN_FIRST_CHARGE_GIFT,
	SMSG_UPDATE_VIP_UNLOCK_FUNCTION,
	SMSG_OBTAIN_FIRST_CHARGE_GIFT_NOTIFY,
	SMSG_OBTAIN_DAY_FIRST_CHARGE_GIFT_NOTIFY,

	SMSG_MULTICOPY_STAGE	= 3900,
	CMSG_MULTICOPY_OPEN,
	SMSG_MULTICOPY_OPEN,
	CMSG_MULTICOPY_OPEN_ROOM,
	SMSG_MULTICOPY_OPEN_ROOM,
	CMSG_MULTICOPY_CREATE_TEAM,
	SMSG_MULTICOPY_CREATE_TEAM,
	CMSG_MULTICOPY_QUICK_JOIN,
	SMSG_MULTICOPY_QUICK_JOIN,
	CMSG_MULTICOPY_JOIN_TEAM,
	SMSG_MULTICOPY_JOIN_TEAM,
	CMSG_MULTICOPY_QUIT_TEAM,
	SMSG_MULTICOPY_QUIT_TEAM,
	CMSG_MULTICOPY_DISBAND_QUEUE,
	SMSG_MULTICOPY_TEAM_UPDATE,
	SMSG_MULTICOPY_DISBAND_QUEUE,
	CMSG_MULTICOPY_START,
	SMSG_MULTICOPY_START,
	CMSG_MULTICOPY_CLOSE_ROOM,
	SMSG_MULTICOPY_CLOSE_ROOM,
	CMSG_MULTICOPY_ADJUST_POS,
	SMSG_MULTICOPY_ADJUST_POS,
	CMSG_MULTICOPY_INVITE,
	SMSG_MULTICOPY_INVITE,

   // SMSG_MAIL_ERROR     = 4000,
    //CMSG_MAIL_OPEN,
    //SMSG_MAIL_OPEN,
    //CMSG_MAIL_SEND,
    //SMSG_MAIL_SEND,
    //CMSG_MAIL_SAVE,
    //SMSG_MAIL_SAVE,
    //CMSG_MAIL_ERASE,
    //SMSG_MAIL_ERASE,
    //SMSG_MAIL_PEND,
    //SMSG_MAIL_RECV,
    //SMSG_INFO_RECV,

	SMSG_MAIL_UNREAD_NOTIFY = 4000,
	CMSG_MAIL_OPEN_MAILBOX,
	SMSG_MAIL_OPEN_MAILBOX,
	CMSG_MAIL_READ,
	SMSG_MAIL_READ,
	CMSG_MAIL_DELETE,
	SMSG_MAIL_DELETE,
	CMSG_MAIL_SEND,
	SMSG_MAIL_SEND,
	SMSG_MAIL_NEW,
	CMSG_MAIL_GET_ATTACH,
	SMSG_MAIL_GET_ATTACH,

	CMSG_OPEN_FRIEND	= 4100,
	SMSG_OPEN_FRIEND,
	CMSG_ADD_FRIEND_BY_GUID,
	CMSG_ADD_FRIEND_BY_NAME,
	SMSG_ADD_FRIEND,
	CMSG_REMOVE_FRIEND,
	SMSG_REMOVE_FRIEND,
	CMSG_ADD_ENEMY_BY_GUID,
	CMSG_ADD_ENEMY_BY_NAME,
	SMSG_ADD_ENEMY,
	CMSG_REMOVE_ENEMY,
	SMSG_REMOVE_ENEMY,
	CMSG_GIVE_ENERGY,
	SMSG_GIVE_ENERGY,
	CMSG_GIVE_FLOWER,
	SMSG_GIVE_FLOWER,
	CMSG_RECV_ENERGY,
	SMSG_RECV_ENERGY,
	CMSG_OPEN_FLOWER_RANK,
	SMSG_OPEN_FLOWER_RANK,
	SMSG_CONFIRM_ADD_FRIEND,
	CMSG_CONFIRM_ADD_FRIEND,
	SMSG_ADD_FRIEND_SUCESS,
	SMSG_ADD_ENEMY_SUCESS,
	SMSG_UPDATE_REVC_ENERGY,
	SMSG_FLOWER_RANK_REWARD,
	CMSG_OBTAIN_FLOWER_RANK_REWARD,
	SMSG_OBTAIN_FLOWER_RANK_REWARD,
	CMSG_GET_CHAT_PLAYER_INFO,
	SMSG_GET_CHAT_PLAYER_INFO,
	SMSG_CONFIRM_ADD_FRIEND_RESULT,
	SMSG_SYSTEM_ADD_FRIEND_NOTIFY,
	CMSG_SYSTEM_ADD_FRIEND_NOTIFY,

	CMSG_ACHIEVEMENT_REQUEST		= 4200,
	SMSG_ACHIEVEMENT_REQUEST,
	SMSG_ACHIEVEMENT_COMPLETE,
	CMSG_GET_REWARD_REQUEST,
	SMSG_GET_REWARD_REQUEST,
	CMSG_GET_DAILY_REWARD_REQUEST,
	SMSG_GET_DAILY_REWARD_REQUEST,
	
	//双修(江湖一杯酒)
	CMSG_OPEN_PRACTICE			= 4300,
	SMSG_OPEN_PRACTICE,
	CMSG_DRINK_WINE,
	SMSG_DRINK_WINE,
	CMSG_WINE_TANK_LEVELUP,
	SMSG_WINE_TANK_LEVELUP,
	CMSG_WINE_TANK_FULL,
	SMSG_WINE_TANK_FULL,
	CMSG_STOMACH_FULL,
	SMSG_STOMACH_FULL,
	CMSG_UNLOCK_WINE_TANK,
	SMSG_UNLOCK_WINE_TANK,
	CMSG_PICK_GOURD,
	SMSG_PICK_GOURD,
	SMSG_STOMACH_VALUE_UPDATE,
	SMSG_GOURD_RIPE_NOTIFY,
	
	//伙伴强化(训练馆)
	CMSG_OPEN_TRAINING		= 4400,
	SMSG_OPEN_TRAINING,
	CMSG_REQUEST_TRAINING,
	SMSG_REQUEST_TRAINING,
	SMSG_TRAINING_ONLINE_NOTIFY,

	CMSG_REQUEST_EXCHANGE	= 4500,
	SMSG_REQUEST_EXCHANGE,

	// 帮会
	CMSG_CREATE_GUILD		= 4600,
	SMSG_CREATE_GUILD,
	CMSG_GUILD_LIST,
	SMSG_GUILD_LIST,
	CMSG_EXACT_SEARCH_GUILD_BY_NAME,
	SMSG_EXACT_SEARCH_GUILD_BY_NAME,
	CMSG_CHECK_GUILD,
	SMSG_CHECK_GUILD,
	CMSG_APPLY_GUILD_LIST,
	SMSG_APPLY_GUILD_LIST,
	CMSG_APPLY_GUILD,
	SMSG_APPLY_GUILD,
	CMSG_CANCEL_APPLY_GUILD,
	SMSG_MYSELF_GUILD_ACTIVITY,
	CMSG_MYSELF_GUILD_MEMBER_LIST,
	SMSG_MYSELF_GUILD_MEMBER_LIST,
	CMSG_MYSELF_GUILD_LOG_LIST,
	SMSG_MYSELF_GUILD_LOG_LIST,
	CMSG_GUILD_APPLICATION_LIST,
	SMSG_GUILD_APPLICATION_LIST,
	CMSG_PROCESS_GUILD_APPLICATION,
	SMSG_PROCESS_GUILD_APPLICATION,
	CMSG_GUILD_NOTICE,
	SMSG_GUILD_NOTICE,
	CMSG_GUILD_BADGE,
	SMSG_GUILD_BADGE,
	CMSG_DEMISE_MEMBER_LIST,
	SMSG_DEMISE_MEMBER_LIST,
	CMSG_DEMISE_JOB,
	SMSG_DEMISE_JOB,
	CMSG_ADJUST_MEMBER_LIST,
	SMSG_ADJUST_MEMBER_LIST,
	CMSG_ADJUST_JOB,
	SMSG_ADJUST_JOB,
	CMSG_ENLIST_MEMBER,
	SMSG_ENLIST_MEMBER,
	CMSG_JOIN_GUILD,
	SMSG_JOIN_GUILD,
	CMSG_DISBAND_GUILD,
	SMSG_DISBAND_GUILD,
	CMSG_QUIT_GUILD,
	SMSG_QUIT_GUILD,
	CMSG_KICK_GUILD,
	SMSG_KICK_GUILD,
	STOL_ADD_GUILD_EXP,
	CMSG_OTHER_GUILD_LIST,
	SMSG_OTHER_GUILD_LIST,
	SMSG_UPDATE_GUILD_NAME,
	CMSG_DELATE_LEADER,
	SMSG_DELATE_LEADER,
	CMSG_DELATE_VOTE,
	SMSG_DELATE_VOTE,
	CMSG_SEE_DELATE_VOTE,
	SMSG_SEE_DELATE_VOTE,
	STOL_DELATE_LEADER,

	// 每日积分
	CMSG_DAILYPOINTS_LIST	= 4800,
	SMSG_DAILYPOINTS_LIST,
	CMSG_COIN_COMPLETE_EVENT,
	SMSG_COIN_COMPLETE_EVENT,
	CMSG_GET_DAILY_REWARD,
	SMSG_GET_DAILY_REWARD,

	//押镖
	CMSG_ESCORT_OPEN		= 4900,
	SMSG_ESCORT_OPEN,
	CMSG_ESCORT_CLOSE,
	SMSG_ESCORT_CLOSE,
	CMSG_ESCORT_MAP_CHANGE,
	SMSG_ESCORT_MAP_CHANGE,
	SMSG_ESCORT_MAP_INFO,
	SMSG_ESCORT_STATE_CHANGE,
	CMSG_ESCORT_QUICK,
	SMSG_ESCORT_QUICK,
	CMSG_ESCORT_CMP_DIR,
	SMSG_ESCORT_CMP_DIR,
	CMSG_ESCORT_AGENCY_LEVELUP,
	SMSG_ESCORT_AGENCY_LEVELUP,
	CMSG_ESCORT_CAR_REFRESH,	
	SMSG_ESCORT_CAR_REFRESH,
	CMSG_ESCORT_CAR_BUY_DIR,
	SMSG_ESCORT_CAR_BUY_DIR,
	CMSG_ESCORT_START,
	SMSG_ESCORT_START,
	CMSG_ESCORT_FRIEND_INFO,
	SMSG_ESCORT_FRIEND_INFO,
	CMSG_ESCORT_INVITE_HELPER,
	SMSG_ESCORT_INVITE_HELPER,
	CMSG_ESCORT_BEINVITE,
	SMSG_ESCORT_BEINVITE,
	SMSG_ESCORT_BEINVITE_NOTIFY,
	CMSG_ESCORT_INVITE_CANCLE,
	SMSG_ESCORT_INVITE_CANCLE,
	CMSG_ESCORT_PRAY,
	SMSG_ESCORT_PRAY,
	SMSG_ESCORT_PRAY_NOTIFY,
	CMSG_ESCORT_ROB,
	SMSG_ESCORT_ROB,
	SMSG_ESCORT_ROB_NOTIFY,
	SMSG_ESCORT_ADD_ENEMY,
	CMSG_ESCORT_RESET_ROB_COOLING,
	SMSG_ESCORT_RESET_ROB_COOLING,
	SMSG_ESCORT_NOTIFY,
	SMSG_ESCORT_FINISH,
	SMSG_ESCORT_TIMES_HELP_CHANGE,
	SMSG_ESCORT_CAR_MAP_CURRENT,
	SMSG_ESCORT_TIMES_LEFT,

	//推图
	SMSG_TOWER_ONLINE_NOTIFY	= 5000,
	CMSG_TOWER_LIST,
	SMSG_TOWER_LIST,
	CMSG_TOWER_OPEN,
	SMSG_TOWER_OPEN,
	CMSG_TOWER_START,
	SMSG_TOWER_START,
	CMSG_TOWER_STOP,
	SMSG_TOWER_STOP,
	CMSG_TOWER_BATTLE,
	SMSG_TOWER_BATTLE,
	CMSG_TOWER_ADD_BUFF,
	SMSG_TOWER_ADD_BUFF,
	CMSG_TOWER_BONUS,
	SMSG_TOWER_BONUS,
	SMSG_TOWER_BONUS_NOTIFY,
	CMSG_TOWER_JUMP_MAP,
	SMSG_TOWER_JUMP_MAP,

	// 酒馆
	CMSG_OPEN_TAVERN			= 5100,
	SMSG_OPEN_TAVERN,
	CMSG_RANDOM_CARD,
	SMSG_RANDOM_CARD,
	CMSG_CHANGE_CARD,
	SMSG_CHANGE_CARD,
	CMSG_GET_RANDOM_REWARD,
	SMSG_GET_RANDOM_REWARD,
	CMSG_RECRULT_ROLE,
	SMSG_RECRULT_ROLE,
	CMSG_CLEAN_UP_CD,
	SMSG_CLEAN_UP_CD,
	CMSG_TAVERN_SHOP_BUY,
	SMSG_TAVERN_SHOP_BUY,
	CMSG_BATCH_RANDOM_CARD,
	SMSG_BATCH_RANDOM_CARD,
	CMSG_BATCH_RANDOM_CARD_100,
	SMSG_BATCH_RANDOM_CARD_100,
	SMSG_NOTIFY_TAVERN_LOG,
	STOL_TAVERN_LOG,
	LTOS_TAVERN_LOG_ALL,

	//梅花桩
	CMSG_PLUM_OPEN				= 5200,
	SMSG_PLUM_OPEN,
	CMSG_PLUM_CHANGE_STEP,
	SMSG_PLUM_CHANGE_STEP,
	CMSG_PLUM_COMPLTE,
	SMSG_PLUM_COMPLTE,
	CMSG_PLUM_START,
	SMSG_PLUM_START,
	CMSG_PLUM_UNDERSTAND,
	SMSG_PLUM_UNDERSTAND,
	SMSG_PLUM_DAY_CHANGE,
	//轻功
	CMSG_DODGE_OPEN,
	SMSG_DODGE_OPEN,
	CMSG_DODGE_INSTALL,
	SMSG_DODGE_INSTALL,
	CMSG_DODGE_PART_LEVELUP,
	SMSG_DODGE_PART_LEVELUP,
	CMSG_DODGE_LEVELUP,
	SMSG_DODGE_LEVELUP,
	SMSG_DODGE_LOGIN,
	SMSG_DODGE_POINT_UPDATE,
	SMSG_DODGE_NEW_UNLOCK,
	CMSG_DODGE_RETURN_QUERY,
	SMSG_DODGE_RETURN_QUERY,
	CMSG_DODGE_RETURN_EXEC,
	SMSG_DODGE_RETURN_EXEC,
	CMSG_DODGE_UNLOCK_BY_GOLD,
	SMSG_DODGE_UNLOCK_BY_GOLD,
	CMSG_PLUM_BATCH,
	SMSG_PLUM_BATCH,


	// 帮会战
	CMSG_OPEN_GUILDBALLTE		= 5300,
	SMSG_OPEN_GUILDBALLTE,
	CMSG_SIGN_UP_GUILDBALLTE,
	SMSG_SIGN_UP_GUILDBALLTE,
	CMSG_CHECK_SIGN_UP_GUILDBATTLE,
	SMSG_CHECK_SIGN_UP_GUILDBATTLE,
	CMSG_CHECK_GUILDBATTLE,
	SMSG_CHECK_GUILDBATTLE,
	CMSG_JOIN_GUILDBALLTE,
	SMSG_JOIN_GUILDBALLTE,
	SMSG_UPDATE_BALLTE_INFO,
	SMSG_UPDATE_BASE_INFO,
	CMSG_START_BATTLE,
	SMSG_START_BATTLE,
	SMSG_UPDATE_LOG_INFO,
	SMSG_SEND_END_GUILDBATTLE,
	CMSG_LEAVE_GUILDBATTLE,
	SMSG_LEAVE_GUILDBATTLE,
	SMSG_REWARD_GUILDBATTLE,
	CMSG_CLIENT_NOTIFY_BATTLE_OVER,
	SMSG_CLIENT_NOTIFY_BATTLE_OVER,
	SMSG_BROAD_OPEN_BATTLING,
	SMSG_BROAD_CLOSE_BATTLING,
	CMSG_GET_GUILDBATTLE_REWARD,
	SMSG_GUILDBATTLE_BROAD_TIME,
	SMSG_BROAD_DEATH_PLAYER,
	SMSG_BROAD_GUILD_JOB,
	SMSG_ALL_PLAYER_GUILD_JOB,
	SMSG_NOTIFY_START_BATTLE,
	SMSG_GET_GUILDBATTLE_REWARD,

	CMSG_GO_FISHING				= 5400,
	SMSG_GO_FISHING,
	SMSG_UPDATE_FISH_TIME,
	CMSG_GAIN_FISH,
	SMSG_GAIN_FISH,
	CMSG_CLEAR_FISH_TIME,
	SMSG_CLEAR_FISH_TIME,
	CMSG_GET_FISH_LEFT_TIME,
	

	//> 阵营战
	SMSG_BATTLEGROUND_PHASE_NOTIFY	= 5500,
	CMSG_BATTLEGROUND_OPEN,
	SMSG_BATTLEGROUND_OPEN,
	CMSG_BATTLEGROUND_SCORES,
	SMSG_BATTLEGROUND_SCORES,
	CMSG_BATTLEGROUND_JOIN,
	SMSG_BATTLEGROUND_JOIN,
	CMSG_BATTLEGROUND_QUIT,
	SMSG_BATTLEGROUND_QUIT,
	CMSG_BATTLEGROUND_PERSONAL_INFO,
	SMSG_BATTLEGROUND_PERSONAL_INFO,
	CMSG_BATTLEGROUND_TEAM_LIST_GET,
	SMSG_BATTLEGROUND_TEAM_LIST_GET,
	CMSG_BATTLEGROUND_MEMBER_LIST_UPDATE,
	SMSG_BATTLEGROUND_MEMBER_LIST_UPDATE,
	CMSG_BATTLEGROUND_TOPLIST,
	SMSG_BATTLEGROUND_TOPLIST,
	CMSG_BATTLEGROUND_STAKE,
	SMSG_BATTLEGROUND_STAKE,
	CMSG_BATTLEGROUND_ATTACH_BUFF,
	SMSG_BATTLEGROUND_ATTACH_BUFF,
	SMSG_BATTLEGROUND_BATTLE,
	CMSG_BATTLEGROUND_PLAYBACK_OVER,
	SMSG_BATTLEGROUND_PLAYBACK_OVER,
	SMSG_BATTLEGROUND_BONUS,
	SMSG_BATTLEGROUND_RECORD,
	SMSG_BATTLEGROUND_BONUS_NOTIFY,
	CMSG_BATTLEGROUND_BONUS,
	SMSG_BATTLEGROUND_BATTLE_START,
	CMSG_BATTLEGROUND_SHORT_INFO,
	SMSG_BATTLEGROUND_SHORT_INFO,
	SMSG_BATTLEGROUND_DEBUFF,
    SMSG_BATTLEGROUND_STAKE_ONLINE_NOTIFY,

	/// 侠侣系统
	CMSG_WIFE_SHIT = 5600,				// 调情
	SMSG_WIFE_SHIT,
	CMSG_WIFE_SHIT_COIN,				// 元宝调情
	SMSG_WIFE_SHIT_COIN,
	CMSG_WIFE_WEAR_EQUIP,				// 穿装备
	SMSG_WIFE_WEAR_EQUIP,
	CMSG_WIFE_UNEQUIP,					// 下装备
	SMSG_WIFE_UNEQUIP,
	CMSG_WIFE_PROTECT,					// 设置侠侣保护
	SMSG_WIFE_PROTECT,
	CMSG_WIFE_INVITE_OPEN,				// 打开春华楼
	SMSG_WIFE_INVITE_OPEN,
	CMSG_WIFE_INVITE_NORMAL,			// 普通邀请 // 废弃
	SMSG_WIFE_INVITE_NORMAL,
	CMSG_WIFE_INVITE_FILTER,			// 行酒令 // 废弃
	SMSG_WIFE_INVITE_FILTER,
	CMSG_WIFE_INVITE_COIN,				// 元宝邀请	// 废弃
	SMSG_WIFE_INVITE_COIN,
	SMSG_CREATE_WIFE,					// 玩家登陆的时候，下发侠侣信息
	SMSG_WIFE_UPDATE_LEVEL,				// 更新侠侣等级信息
	SMSG_WIFE_UPDATE_FATEPOINT,			// 更新玩家缘分点
	CMSG_WIFE_GET,						// 召唤
	SMSG_WIFE_GET,
	CMSG_WIFE_SHIT_LEVEL_NORMAL,		// 一键升级缘分点版
	SMSG_WIFE_SHIT_LEVEL_NORMAL,
	CMSG_WIFE_SHIT_LEVEL_COIN,			// 一键升级元宝版
	SMSG_WIFE_SHIT_LEVEL_COIN,
	CMSG_WIFE_GET_FREE,					// 招募一个侠侣
	SMSG_WIFE_GET_FREE,
	CMSG_WIFE_SELL,						// 兑换侠侣
	SMSG_WIFE_SELL,
	CMSG_WIFE_GET_FULL_PROGRESS,		// 招募满进度侠侣
	SMSG_WIFE_GET_FULL_PROGRESS,
	CMSG_WIFE_FOLLOW,					// 设置侠侣跟随
	SMSG_WIFE_FOLLOW,
	SMSG_WIFE_UPDATE_FOLLOW,			// 跟随侠侣更新

	// activity; // 模板活动
	SMSG_ACTIVITY_ALL_ACTIVITY = 5700,			// 下发玩家当前所有的模板活动
	SMSG_ACTIVITY_ADD_ACTIVITY,			// 实时通知客户端，添加开启活动
	SMSG_ACTIVITY_PROGRESS,				// 实时推送客户端，某活动进度的更新
	SMSG_ACTIVITY_REMOVE_ACTIVITY,		// 实时推送，活动结束消息
	SMSG_ACTIVITY_PRIZE,				// 实时推送可以领取的奖励
	SMSG_ACTIVITY_PRIZE_OFFLINE,		// 实时推送，活动下线时，尚未领取的奖励（需要配置自动下发奖励）
	CMSG_ACTIVITY_GET_PRIZE,			// 客户端领奖协议
	SMSG_ACTIVITY_GET_PRIZE,			// 客户端领奖协议返回消息
	CMSG_ACTIVITY_TIME_REMAIN,
	SMSG_ACTIVITY_TIME_REMAIN,
	CMSG_ACTIVITY_CYCLE,				// 
	SMSG_ACTIVITY_CYCLE,				// 活动轮次推送
	SMSG_ACTIVITY_CYCLE_COMPLETE,		// 活动当前轮次完成情况推送。
	CMSG_ACTIVITY_VIEW_CHALLENGE,		// 查看
	SMSG_ACTIVITY_VIEW_CHALLENGE,

	// -------武林英雄大会(begin)----------------
	CMSG_OPEN_QUALIFYBATTLE = 5800,
	SMSG_OPEN_QUALIFYBATTLE,
	CMSG_SIGN_UP_QUALIFYBATTLE,
	SMSG_SIGN_UP_QUALIFYBATTLE,
	CMSG_SEE_MYSELF_RECORD,
	SMSG_SEE_MYSELF_RECORD,
	CMSG_SEE_QUALIFYBATTLE,
	SMSG_SEE_QUALIFYBATTLE,
	CMSG_BUY_CHIPS,
	SMSG_BUY_CHIPS,
	CMSG_PROMOION_BETS,
	SMSG_PROMOION_BETS,
	CMSG_CHAMPION_BETS,
	SMSG_CHAMPION_BETS,
	CMSG_SEE_OTHERS_RECORD,
	SMSG_SEE_OTHERS_RECORD,
	SMSG_QUALIFY_NOTIFY,
	SMSG_QUALIFYBATTLE_REWARD,
	CMSG_GET_QUALIFYBATTLE_REWARD,
	SMSG_GET_QUALIFYBATTLE_REWARD,
	SMSG_BROADCAST_QUALIFY_STAGE,

	STOA_BUY_CHIPS,
	STOA_CHAMPION_BETS,
	ATOS_REDUCE_RESOURCE,
	ATOS_ADD_RESOURCE,
	STOA_QUALIFY_START,
	STOA_QUALIFY_RESET,
	STOA_SIGN_UP_QUALIFY,
	STOA_PLAYER_IS_ONLINE,
	ATOS_QUALIFY_REWARD,
	STOA_QUALIFY_REWARD,
	STOA_PLAYER_LEVEL_UP,

	CPMSG_INIT_QUALIFY		= 5900,
	CPMSG_LOAD_QUALIFY,
	CPMG_RESET_QUALIFY,
	CPMG_CHECK_QUALIFY,
	CPMSG_QUALIFY_MEMBER,
	CPMSG_SIGN_UP_INFO,

	CMSG_CROSS_QUALIFYBATTLE,
	SMSG_CROSS_QUALIFYBATTLE,
	CMSG_CROSS_QUALIFYLOGS,
	SMSG_CROSS_QUALIFYLOGS,
	CMSG_CROSS_SIGN_UP_QUALIFYBATTLE,
	SMSG_CROSS_SIGN_UP_QUALIFYBATTLE,
	CMSG_CROSS_BETS,
	CMSG_CROSS_CHANNEL_NOTIFY,
	CMSG_CROSS_PLAYER_NOTIFY,
	CMSG_CROSS_QUALIFY_NOTIFY,
	CMSG_CROSS_ADD_LUCKY_MONEY,
	CMSG_CROSS_ADD_BETS_PLAYER,
	SMSG_CROSS_LUCKY,
	SMSG_CROSS_BATTLE_LOG,
	SMSG_CROSS_QUALIFY_ROUND_POSITION,
	SMSG_CROSS_GROUP_PLAYER,
	SMSG_CROSS_ROUND_TIME,
	CMSG_CROSS_GET_REWARD,
	SMSG_CROSS_EXTRA_PLAYER_INFO,
	SMSG_CROSS_QUALIFYBATTLE_START,
	SMSG_CROSS_QUALIFYBATTLE_RESET,
	SMSG_CROSS_SET_SIGN_UP,
	CMSG_CROSS_OPEN_SERVICE,
	SMSG_CROSS_OPEN_SERVICE,
	CMSG_CROSS_REGISTER,
	SMSG_CROSS_REGISTER,

	CPMSG_CLOSE_THISSTATE,	// 插件A请求关闭c插件的状态机运行

	CNMSG_QUALIFY_NOTIFY	= 6000,
	CNMSG_WEED_OUT_DATA,
	CNMSG_QUALIFY_DATA,
	CNMSG_QUALIFY_ROUND_POSITION,
	CNMSG_GROUP_PLAYER,
	CNMSG_ROUND_TIME,
	CNMSG_FIRST_LOAD_ERROR_PLAYER,
	// -------武林英雄大会(end)----------------


    // 海捕文书
    CMSG_ARREST_DAILY_INFO	= 6100,
    SMSG_ARREST_DAILY_INFO,
    CMSG_ARREST_SHARED_INFO,
    SMSG_ARREST_SHARED_INFO,
    CMSG_ARREST_DAILY_START,
    SMSG_ARREST_DAILY_START,
    CMSG_ARREST_BONUS,
    SMSG_ARREST_BONUS,
    CMSG_ARREST_DAILY_BROADCAST,
    SMSG_ARREST_DAILY_BROADCAST,
    CMSG_ARREST_DAILY_REFRESH,
    SMSG_ARREST_DAILY_REFRESH,
    CMSG_ARREST_DAILY_BUY_TIMES,
    SMSG_ARREST_DAILY_BUY_TIMES,
    CMSG_ARREST_DAILY_JOIN_TEAM,
    SMSG_ARREST_DAILY_JOIN_TEAM,
    CMSG_ARREST_DAILY_QUIT_TEAM,
    SMSG_ARREST_DAILY_QUIT_TEAM,
    CMSG_ARREST_DAILY_KICK_OUT_TEAM,
    SMSG_ARREST_DAILY_KICK_OUT_TEAM,
    CMSG_ARREST_DAILY_INVITE_FRIEND,
    SMSG_ARREST_DAILY_INVITE_FRIEND,
    SMSG_ARREST_DAILY_CONFIRM_INVITE_FRIEND,
    CMSG_ARREST_DAILY_CONFIRM_INVITE_FRIEND,
    CMSG_ARREST_DAILY_MEMBER_EXCHANGE_ROLE,
    SMSG_ARREST_DAILY_MEMBER_EXCHANGE_ROLE,
    CMSG_ARREST_DAILY_CHANGE_ROLE_POS,
    SMSG_ARREST_DAILY_CHANGE_ROLE_POS,
    CMSG_ARREST_DAILY_TEAM_MEMBER_UPDATE,
    SMSG_ARREST_DAILY_TEAM_MEMBER_UPDATE,
    SMSG_ARREST_DAILY_ORDER_UPDATE,
    CMSG_ARREST_DISMISS_TEAM,
    SMSG_ARREST_DISMISS_TEAM,
    CMSG_ARREST_CREATE_TEAM,
    SMSG_ARREST_CREATE_TEAM,
    SMSG_ARREST_TEAM_DISMISSED,
    SMSG_ARREST_SHARED_ORDER_UPDATE,
    SMSG_ARREST_PROGRESS_TIPS,


	// 丹药
	CMSG_OPEN_PELLET		= 6200,
	SMSG_OPEN_PELLET,
	CMSG_SWALLOW_PELLET,
	SMSG_SWALLOW_PELLET,


	
	// 秘境奇缘：
	SMSG_MAZE_EXPLORE_POINT = 6300,					// 推送探索点数
	SMSG_MAZE_EXPLORE_POINT_BUY_NUM,				// 推送探索点购买次数
	SMSG_MAZE_HAS_TIMEMAZE,							// 推送是否存在限时秘境开启
	SMSG_MAZE_UNLOCK_A_MAZE,						// 推送秘境解锁通知

	CMSG_MAZE_OPEN,									// 打开秘境面板
	SMSG_MAZE_OPEN,
	CMSG_MAZE_BUY_EXPLORE_POINT,					// 购买探索点数一次
	SMSG_MAZE_BUY_EXPLORE_POINT,
	CMSG_MAZE_BUY_EXPLORE_NUM,						// 购买探索次数
	SMSG_MAZE_BUY_EXPLORE_NUM,
	CMSG_MAZE_RESET,								// 重置迷宫
	SMSG_MAZE_RESET,
	CMSG_MAZE_ENTER_MAZE,							// 进入迷宫
	SMSG_MAZE_ENTER_MAZE,
	CMSG_MAZE_ENTER_ROOM,							// 跳迷宫房间
	SMSG_MAZE_ENTER_ROOM,
	CMSG_MAZE_QUIT,									// 离开迷宫
	SMSG_MAZE_QUIT,
	SMSG_MAZE_KICK,									// 踢出迷宫（推送）
	CMSG_MAZE_UNLOCK_ROOM,							// 钥匙解锁迷宫房间
	SMSG_MAZE_UNLOCK_ROOM,
	CMSG_MAZE_OPEN_HIDE_TRIP,						// 打开隐藏机关
	SMSG_MAZE_OPEN_HIDE_TRIP,
	CMSG_MAZE_OPEN_TRIP,							// 开启机关
	SMSG_MAZE_OPEN_TRIP,
	CMSG_MAZE_BEAT_ENEMY,							// 迷宫战斗
	SMSG_MAZE_BEAT_ENEMY,
	CMSG_MAZE_ROOM_CLEAR,							// 直接完成迷宫房间
	SMSG_MAZE_ROOM_CLEAR,
	CMSG_MAZE_GET_REWARD,							// 领取宝箱
	SMSG_MAZE_GET_REWARD,
	SMSG_MAZE_ROOM_OPEN,							// 推送迷宫房间开启
	SMSG_MAZE_NEW_ITEM,								// 推送
	SMSG_MAZE_PRIZE_ITEM,							// 迷宫中获得的物品

    // 开服活动
    SMSG_OPENACTIVITY_ACCONLINE_NOTIFY = 6400,
    SMSG_OPENACTIVITY_SECTION_NOTIFY,
    SMSG_OPENACTIVITY_FIRSTBUY_NOTIFY,
    SMSG_OPENACTIVITY_ACCBUY_NOTIFY,
    SMSG_OPENACTIVITY_NEXTDAY_NOTIFY,
    SMSG_OPENACTIVITY_FUTURE_NOTIFY,
    CMSG_OPENACTIVITY_SHORTCUT_NOTIFY,
    SMSG_OPENACTIVITY_SHORTCUT_NOTIFY,
    CMSG_OPENACTIVITY_BONUS,
    SMSG_OPENACTIVITY_BONUS,
    CMSG_OPENACTIVITY_FUTURE_INPUT,
    SMSG_OPENACTIVITY_FUTURE_INPUT,
    SMSG_OPENACTIVITY_OPEN_DAY,
    CMSG_OPENACTIVITY_BILL_NOTIFY,
    SMSG_OPENACTIVITY_BILL_NOTIFY,
    SMSG_OPENACTIVITY_YD_STATE,
    SMSG_OPENACTIVITY_YD_BONUS,
    CMSG_OPENACTIVITY_YD_STATE,
    SMSG_OPENACTIVITY_ONLINE_DAYS,

	// 替身娃娃
	SMSG_AMAH_STATE = 6500,								// 推送玩家替身娃娃状态
	CMSG_AMAH_SET_STATE,							// 设置或者取消替身娃娃
	SMSG_AMAH_SET_STATE,							// 

	AMAH_REDUCE_GOLD = 6590,						// 扣减元宝异步返回消息



	// 开服活动
	SMSG_OPEN_ACT_SHINE = 6600,						// 活动是否亮显
	SMSG_OPEN_ACT_SHOW,								// 是否存在需要显示的活动
	CMSG_OPEN_ACT_STATE,							// 打开活动面板
	SMSG_OPEN_ACT_STATE,
	CMSG_OPEN_ACT_VIEW,								// 查看某活动
	SMSG_OPEN_ACT_VIEW,
	CMSG_OPEN_ACT_GET_PRIZE,
	SMSG_OPEN_ACT_GET_PRIZE,


	// 称号系统
	SMSG_TITLE_NEW = 6700,							// 推送新的称号
	SMSG_TITLE_RELOCK,								// 称号重新被锁定
	CMSG_TITLE_OPEN,								// 打开称号面板
	SMSG_TITLE_OPEN,								//
	CMSG_TITLE_QUERY,								// 查询称号
	SMSG_TITLE_QUERY,
	CMSG_TITLE_ITEM,								// 物品解锁
	SMSG_TITLE_ITEM,
	CMSG_TITLE_SET_CURRENT,							// 设置当前称号
	SMSG_TITLE_SET_CURRENT,
	CMSG_TITLE_RESET,								// 取消当前称号
	SMSG_TITLE_RESET,
	CMSG_TITLE_ENABLE,								// 设置当前称号中属性生效的称号
	SMSG_TITLE_ENABLE,
	SMSG_TITLE_INIT,								// 上线推送玩家当前称号的生效称号

    // 排行榜
    CMSG_RANKING_QUERY_BONUS    = 6800,
    SMSG_RANKING_QUERY_BONUS,
    CMSG_RANKING_GET_BONUS,
    SMSG_RANKING_GET_BONUS,
    CMSG_RANKING_GET_LIST,
    SMSG_RANKING_GET_LIST,
    SMSG_RANKING_NOTIFY,


	// 切磋
	CMSG_INITIATIVE_EXCHANGE		= 6900,
	SMSG_INITIATIVE_EXCHANGE,
	CMSG_CHANNEL_EXCHANGE,
	SMSG_CHANNEL_EXCHANGE,
	CMSG_ACCEPT_INITIATIVE_EXCHANGE,
	SMSG_ACCEPT_INITIATIVE_EXCHANGE,
	CMSG_ACCEPT_CHANNEL_EXCHANGE,
	SMSG_ACCEPT_CHANNEL_EXCHANGE,
	CMSG_CANCEL_EXCHANGE,
	SMSG_CANCEL_EXCHANGE,
	CMSG_RESET_EXCHANGE,
	SMSG_BROADCAST_EXCHANGE,
	CMSG_EXCHANGE_REWARD_NUM,
	SMSG_EXCHANGE_REWARD_NUM,
	LTOSMSG_EXCHAGE_REWARD,
	SMSG_RESET_EXCHANGE,

	// 五绝
	SMSG_SPLENDID_START			= 7000,
	CMSG_SPLENDID_OPEN,
	SMSG_SPLENDID_OPEN,
	CMSG_SPLENDID_VOTE_OPEN,
	SMSG_SPLENDID_VOTE_OPEN,
	CMSG_SPLENDID_VOTE,
	SMSG_SPLENDID_VOTE,
	SMSG_SPLENDID_VOTE_NOTIFY,
	CMSG_SPLENDID_CLEAN_TIME,
	SMSG_SPLENDID_CLEAN_TIME,
	CMSG_SPLENDID_SET_REWARD,
	SMSG_SPLENDID_SET_REWARD,
	CMSG_SPLENDID_APPEND_REWARD,
	SMSG_SPLENDID_APPEND_REWARD,
	CMSG_SPLENDID_CANVASS,
	SMSG_SPLENDID_CANVASS,
	CMSG_SPLENDID_WORSHIP,
	SMSG_SPLENDID_WORSHIP,
	CMSG_SPLENDID_GET_REWARD,
	SMSG_SPLENDID_GET_REWARD,
	SMSG_SPLENDID_CAN_GET_REWARD,

	//剑冢
	CMSG_JIANZHONG_OPEN = 7100,
	SMSG_JIANZHONG_OPEN,
	CMSG_JIANZHONG_CLOSE,
	SMSG_JIANZHONG_CLOSE,
	CMSG_JIANZHONG_OPEN_ROOM,
	SMSG_JIANZHONG_OPEN_ROOM,
	CMSG_JIANZHONG_CLOSE_ROOM,
	SMSG_JIANZHONG_CLOSE_ROOM,
	CMSG_JIANZHONG_ROB,
	SMSG_JIANZHONG_ROB,
	CMSG_JIANZHONG_BUY_TIMES,
	SMSG_JIANZHONG_BUY_TIMES,
	SMSG_JIANZHONG_ROOM_PERSONS_UPDATE,
	SMSG_JIANZHONG_POS_INFO,
	SMSG_JIANZHONG_NOTIFY,
	SMSG_JIFEN_UPDATE,
	SMSG_JIANZHONG_START,
	SMSG_JIANZHONG_END,
	SMSG_JIANZHONG_BE_ROBBED,
	
	// 推送
	SMSG_BROADCAST_PUSH	= 7200,
	SMSG_TOUCH_PUSH,
	CMSG_BUY_PUSH_ITEM,
	SMSG_BUY_PUSH_ITEM,
	CMSG_BROADCAST_PUSH,
	

	// 玩家充值任务：
	SMSG_CHARGEQUEST_STATE = 7300,		// 玩家充值任务。
	CMSG_CHARGEQUEST_GET_PRIZE,			// 领取奖励
	SMSG_CHARGEQUEST_GET_PRIZE,			// 
	SMSG_CHARGEQUEST_CHARGECOIN,		// 通知当前充值元宝数

	// 开服活动1（vip活动和冲级王活动）
	SMSG_OPENACT_VIP_HAS_PRIZE = 7400,	// vip 活动是否有奖励
	SMSG_OPENACT_NEWKING_HAS_PRIZE,		// 新人王活动是否有奖励
	SMSG_OPENACT_VIP_HAS_ACT,			// vip 活动是否需要显示
	SMSG_OPENACT_NEWKING_HAS_ACT,		// 新人王活动是否需要显示
	CMSG_OPENACT_VIP_OPEN,				// 查看vip活动状态
	SMSG_OPENACT_VIP_OPEN,		
	CMSG_OPENACT_NEWKING_OPEN,			// 查看新人王活动状态
	SMSG_OPENACT_NEWKING_OPEN,
	CMSG_OPENACT1_VIEW_VIP,				// 查看VIP活动
	SMSG_OPENACT1_VIEW_VIP,
	CMSG_OPENACT1_VIEW_NEWKING,			// 查看新人王活动
	SMSG_OPENACT1_VIEW_NEWKING,
	CMSG_OPENACT1_VIP_GETPRIZE,			// VIP活动领奖
	SMSG_OPENACT1_VIP_GETPRIZE,
	CMSG_OPENACT1_NEWKING_GETPRIZE,		// 新人王活动领奖
	SMSG_OPENACT1_NEWKING_GETPRIZE,


	// 明教试炼：
	SMSG_TRIAL_HASPRIZE	= 7500,				// 是否存在奖励
	SMSG_TRIAL_HASTIMES,					// 剩余可用次数
	SMSG_TRIAL_FIRST_PLAYER,				// 主动通知第一个击杀
	SMSG_TRIAL_FAST_PLAYER,					// 主动通知最快击杀
	CMSG_TRIAL_OPEN,						// 打开面板
	SMSG_TRIAL_OPEN,
	CMSG_TRIAL_BUY_ATTACK_TIME,				// 购买挑战次数
	SMSG_TRIAL_BUY_ATTACK_TIME,
	CMSG_TRIAL_ENTER_COPY,					// 记录某个副本
	SMSG_TRIAL_ENTER_COPY,
	CMSG_TRIAL_VIEW_RECORD,					// 查看关卡祖记录
	SMSG_TRIAL_VIEW_RECORD,
	CMSG_TRIAL_FIGHT_STAGE,					// 攻击某关卡
	SMSG_TRIAL_FIGHT_STAGE,
	CMSG_TRIAL_WIPE_START,					// 开始扫荡 （服务器记录冷却时间）
	SMSG_TRIAL_WIPE_START,					
	CMSG_TRIAL_WIPE_STAGE,					// 扫荡某关卡
	SMSG_TRIAL_WIPE_STAGE,
	CMSG_TRIAL_CLEAR_WIPE_COOL,				// 清理冷却时间
	SMSG_TRIAL_CLEAR_WIPE_COOL,				
	CMSG_TRIAL_VIP_WIP,						// vip扫荡 （消息体为cmsg_trial_clear_wipe_cool，返回消息是smsg_trial_clear_wipe_cool）
	CMSG_TRIAL_GET_FIRST_PRIZE,				// 领取第一次击杀的奖励
	SMSG_TRIAL_GET_FIRST_PRIZE,
	SMSG_TRIAL_COPY_TIMES,					// 主动通知副本剩余次数


    CMSG_SHENGHUOLING_INFO = 7600,
    SMSG_SHENGHUOLING_INFO,
    SMSG_SHENGHUOLING_BLESS_TIMES,
    CMSG_SHENGHUOLING_FRAGMENT,
    SMSG_SHENGHUOLING_FRAGMENT,
    CMSG_SHENGHUOLING_LEVEL,
    SMSG_SHENGHUOLING_LEVEL,
    CMSG_SHENGHUOLING_STAGE,
    SMSG_SHENGHUOLING_STAGE,
    CMSG_SHENGHUOLING_BLESS,
    SMSG_SHENGHUOLING_BLESS,

	// 符文
	CMSG_OPEN_RUNES		= 7700,
	SMSG_OPEN_RUNES,
	CMSG_UNLOCK_RUNES,
	SMSG_UNLOCK_RUNES,
	CMSG_REFINE_RUNES,
	SMSG_REFINE_RUNES,
	CMSG_LEVELUP_RUNES,
	SMSG_LEVELUP_RUNES,
	CMSG_BLESSING_FORMATION,
	SMSG_BLESSING_FORMATION,
	CMSG_CLASSUP_RUNES,
	SMSG_CLASSUP_RUNES,
	CMSG_STONE_SWAP_FIRE,
	SMSG_STONE_SWAP_FIRE,
	CMSG_ROLE_BINDING_RUNES,
	SMSG_ROLE_BINDING_RUNES,
	CMSG_ROLE_UNINSTALL_RUNES,
	SMSG_ROLE_UNINSTALL_RUNES,


    // 武魂产出
    CMSG_SOULPVE_INFO   = 7800,
    SMSG_SOULPVE_INFO,
    CMSG_SOULPVE_BATTLE,
    SMSG_SOULPVE_BATTLE,
    CMSG_SOULPVE_CRUSH,
    SMSG_SOULPVE_CRUSH,
    CMSG_SOULPVE_ROB,
    SMSG_SOULPVE_ROB,
    CMSG_SOULPVE_RESET,
    SMSG_SOULPVE_RESET,
    CMSG_SOULPVE_BUY_LOSE_LIFE,
    SMSG_SOULPVE_BUY_LOSE_LIFE,
    CMSG_SOULPVE_BUY_RESET_LIFE,
    SMSG_SOULPVE_BUY_RESET_LIFE,
    SMSG_SOULPVE_FRAG,
    
	// 武魂
	CMSG_OPEN_SOUL		= 7900,
	SMSG_OPEN_SOUL,
	CMSG_UNLOCK_SOUL,
	SMSG_UNLOCK_SOUL,
	CMSG_RANDOM_SOUL,
	SMSG_RANDOM_SOUL,
	CMSG_BATCH_SOUL,
	SMSG_BATCH_SOUL,
	CMSG_SAVE_BATCH_SOUL,
	SMSG_SAVE_BATCH_SOUL,
	CMSG_GATHER_SOUL,
	SMSG_GATHER_SOUL,
	CMSG_ROLE_BINDING_SOUL,
	SMSG_ROLE_BINDING_SOUL,
	CMSG_ROLE_UNINSTALL_SOUL,
	SMSG_ROLE_UNINSTALL_SOUL,
	CMSG_CANCEL_BATCH_SOUL,

	//2v2
	//队伍管理
	CMSG_PAIR_OPEN_TEAM		= 8000,
	SMSG_PAIR_OPEN_TEAM,
	CMSG_PAIR_REQUEST_LIST,
	SMSG_PAIR_REQUEST_LIST,
	CMSG_PAIR_ALL_TEAM,
	SMSG_PAIR_ALL_TEAM,
	CMSG_PAIR_CREATE_TEAM,
	SMSG_PAIR_CREATE_TEAM,
	CMSG_PAIR_DISBAND_TEAM,
	SMSG_PAIR_DISBAND_TEAM,
	CMSG_PAIR_JOIN_TEAM,
	SMSG_PAIR_JOIN_TEAM_REQUEST,
	CMSG_PAIR_JOIN_TEAM_REPLY,
	SMSG_PAIR_JOIN_TEAM,
	CMSG_PAIR_INVITE,
	SMSG_PAIR_INVITE,
	CMSG_PAIR_LEAVE,
	SMSG_PAIR_LEAVE,
	CMSG_PAIR_KICK, 
	SMSG_PAIR_KICK, 
	CMSG_PAIR_OPEN_FORM,
	SMSG_PAIR_OPEN_FORM,
	CMSG_PAIR_CHANGE_FORM,
	SMSG_PAIR_CHANGE_FORM,
	SMSG_PAIR_JOIN_TEAM_REPLY,
	CMSG_PAIR_REPLAY_CANCLE,
	SMSG_PAIR_REPLAY_CANCLE,
	CMSG_PAIR_REPLAY_REFUSE_ALL,
	SMSG_PAIR_REPLAY_REFUSE_ALL,

	//赛事管理
	CMSG_PAIR_OPEN		= 8100,
	SMSG_PAIR_OPEN,
	CMSG_PAIR_SIGN_UP,
	SMSG_PAIR_SIGN_UP,
	CMSG_PAIR_SEE_MYSELF_RECORD,
	SMSG_PAIR_SEE_MYSELF_RECORD,
	CMSG_PAIR_SEE,
	SMSG_PAIR_SEE,
	CMSG_PAIR_BETS,
	SMSG_PAIR_BETS,

	CMSG_PAIR_SEE_OTHERS_RECORD,
	SMSG_PAIR_SEE_OTHERS_RECORD,
	SMSG_PAIR_NOTIFY,
	SMSG_PAIR_REWARD,
	CMSG_PAIR_GET_REWARD,
	SMSG_PAIR_GET_REWARD,
	SMSG_PAIR_BROADCAST_STAGE,

	//
	CPMSG_PAIR_INIT,
	CPMSG_PAIR_LOAD,
	CPMSG_PAIR_RESET,
	CPMSG_PAIR_CHECK,
	CPMSG_PAIR_MEMBER,
	CPMSG_PAIR_SIGN_UP_INFO,

	//战斗
	CMSG_PAIR_CROSS_DATA,
	SMSG_PAIR_CROSS_DATA,
	CMSG_PAIR_CROSS_LOGS,
	SMSG_PAIR_CROSS_LOGS,
	CMSG_PAIR_CROSS_SIGN_UP,
	SMSG_PAIR_CROSS_SIGN_UP,
	CMSG_PAIR_CROSS_BETS,
	CMSG_PAIR_CROSS_CHANNEL_NOTIFY,
	CMSG_PAIR_CROSS_PLAYER_NOTIFY,
	CMSG_PAIR_CROSS_NOTIFY,
	CMSG_PAIR_CROSS_ADD_LUCKY_MONEY,
	CMSG_PAIR_CROSS_ADD_BETS_PLAYER,
	SMSG_PAIR_CROSS_LUCKY,
	SMSG_PAIR_CROSS_BATTLE_LOG,
	SMSG_PAIR_CROSS_ROUND_POSITION,
	SMSG_PAIR_CROSS_GROUP_PLAYER,
	SMSG_PAIR_CROSS_ROUND_TIME,
	CMSG_PAIR_CROSS_GET_REWARD,
	SMSG_PAIR_CROSS_EXTRA_PLAYER_INFO,
	SMSG_PAIR_CROSS_START,
	SMSG_PAIR_CROSS_RESET,
	SMSG_PAIR_CROSS_SET_SIGN_UP,
	CMSG_PAIR_CROSS_OPEN_SERVICE,
	SMSG_PAIR_CROSS_OPEN_SERVICE,

	CNMSG_PAIR_NOTIFY			= 8200,
	CNMSG_PAIR_WEED_OUT_DATA,
	CNMSG_PAIR_DATA,
	CNMSG_PAIR_ROUND_POSITION,
	CNMSG_PAIR_GROUP_PLAYER,
	CNMSG_PAIR_ROUND_TIME,

	STOA_PAIR_BETS,
	ATOS_PAIR_REDUCE_RESOURCE,
	ATOS_PAIR_ADD_RESOURCE,
	STOA_PAIR_START,
	STOA_PAIR_RESET,
	STOA_PAIR_SIGN_UP,
	ATOS_PAIR_REWARD,
	STOA_PAIR_REWARD,

	STOA_PAIR_PLAYER_IS_ONLINE,
	STOA_PAIR_PLAYER_LEVEL_UP,
	LTOS_PAIR_CREATE_TEAM,
	STOL_PAIR_CREATE_TEAM,
	//line to local
	LTOA_PAIR_SIGN_UP,
	ATOL_PAIR_SIGN_UP,
	LTOA_CHANGE_FROM,


	// 三天登陆领奖
	CMSG_LOGINGIFT_LOTTERY = 8300, // 抽奖消息
	SMSG_LOGINGIFT_LOTTERY,
	CMSG_LOGINGIFT_GET_PRIZE,	// 领奖消息
	SMSG_LOGINGIFT_GET_PRIZE,
	SMSG_LOGINGIFT_STATE, // 上线状态推送消息
	CMSG_LOGINGIFT_MONEY_LOTTERY, // 银两抽奖
	SMSG_LOGINGIFT_MONEY_LOTTERY, 
	CMSG_LOGINGIFT_GET_MONEY_PRIZE, // 银两领奖
	SMSG_LOGINGIFT_GET_MONEY_PRIZE, 


	// 超级战力
	SMSG_SUPERPOWER_STATE = 8400,				// 上线推送所有目标的状态
	SMSG_SUPERPOWER_PROGRESS,			// 主动推送任务进度
	SMSG_SUPERPOWER_QUEST_COMPLETE,		// 某目标当前任务完成通知
	CMSG_SUPERPOWER_QUEST_PRIZE,		// 领取任务奖励
	SMSG_SUPERPOWER_QUEST_PRIZE,
	CMSG_SUPERPOWER_TARGET_PRIZE,		// 领取目标奖励
	SMSG_SUPERPOWER_TARGET_PRIZE,
	CMSG_SUPERPOWER_CLEAR,				// 立即完成目标
	SMSG_SUPERPOWER_CLEAR,
	CMSG_SUPERPOWER_SET_TRACK,			// 设置为追踪
	SMSG_SUPERPOWER_SET_TRACK,

	// 特权系统
	CMSG_OPEN_GOLDCARD = 8500,
	SMSG_OPEN_GOLDCARD,
	SMSG_UPDATE_GOLDCARD,
	CMSG_BUY_GOLDCARD,
	SMSG_BUY_GOLDCARD,
	CMSG_NEW_REWARD_GOLDCARD,
	SMSG_NEW_REWARD_GOLDCARD,
	CMSG_OLD_REWARD_GOLDCARD,
	SMSG_OLD_REWARD_GOLDCARD,

    // 幸运大转盘
    SMSG_TURNTABLE_STAGE_NOTIFY =8600,
    CMSG_TURNTABLE_RUN,
    LTOS_TURNTABLE_RUN,
    SMSG_TURNTABLE_RUN,
    CMSG_TURNTABLE_INFO,
    SMSG_TURNTABLE_INFO,
    SMSG_TURNTABLE_TICKET,
    SMSG_TURNTABLE_UPDATE_RECORD,

	
	// talent.资质
	CMSG_TALENT_OPEN = 8700,			// 打开资质面板
	SMSG_TALENT_OPEN,
	CMSG_TALENT_RANDOM_TALENT_NORMAL,	// 物品随机资质
	SMSG_TALENT_RANDOM_TALENT_NORMAL,
	CMSG_TALENT_RANDOM_TALENT_COIN,		// 元宝随机资质
	SMSG_TALENT_RANDOM_TALENT_COIN,
	CMSG_TALENT_RANDOM_CLR_NORMAL,		// 物品随机颜色
	SMSG_TALENT_RANDOM_CLR_NORMAL,
	CMSG_TALENT_RANDOM_CLR_COIN,		// 元宝随机颜色
	SMSG_TALENT_RANDOM_CLR_COIN,
	CMSG_TALENT_UNLOCK,					// 提前解锁资质栏
	SMSG_TALENT_UNLOCK,
	CMSG_TALENT_SAVE,					// 保存当前资质
	SMSG_TALENT_SAVE,
	CMSG_TALENT_CANCEL,					// 取消保存当前资质
	SMSG_TALENT_CANCEL,

    // 坐骑
    CMSG_HORSE_INFO = 8800,
    SMSG_HORSE_OWNED,
    CMSG_HORSE_GETON,
    SMSG_HORSE_GETON,
    SMSG_HORSE_RIDE,
    CMSG_HORSE_TRANINING,
    SMSG_HORSE_TRAINING,
    CMSG_HORSE_LEVELUP,
    SMSG_HORSE_LEVELUP,
    SMSG_HORSE_HORSEMANSHIP,
    SMSG_HORSE_RANCH,
    SMSG_HORSE_HELP,
    CMSG_HORSE_HELP_REFRESH,
    SMSG_HORSE_HELP_REFRESH,
    CMSG_HORSE_COLOR_REFRESH,
    SMSG_HORSE_COLOR_REFRESH,
    SMSG_HORSE_AMOUNT,
    CMSG_HORSE_BIND_PARTNER,
    SMSG_HORSE_BIND_PARTNER,
    SMSG_UPDATE_HORSE_ID,
    CMSG_HORSE_SHOW,
    SMSG_HORSE_SHOW,

	// qq 推广
	SMSG_QQSHARE_OPEN = 8900, // 上线推送分享信息
	CMSG_QQSHARE_SHARED, // 客户端通知服务器执行了一次分享
	CMSG_QQSHARE_GET_PRIZE,
	SMSG_QQSHARE_GET_PRIZE,

	SMSG_QQBRAG_PRIZE = 8930, // 推送炫耀奖励
	CMSG_QQBRAG_GENERATE_PRIZE,
	CMSG_QQBRAG_GET_PRIZE,
	SMSG_QQBRAG_GET_PRIZE,

	// 
	CMSG_QQINVITE_OPEN = 8960,
	SMSG_QQINVITE_OPEN,
	CMSG_QQINVITE_GET_PRIZE,
	SMSG_QQINVITE_GET_PRIZE,
	CMSG_QQINVITE_FRIENDS,
	SMSG_QQINVITE_FRIENDS,
	CMSG_QQINVITE_GENERATE_PRIZE,
	
	CMSG_QQ_INSTALLER = 8990,
	SMSG_QQ_INSTALLER,

	//
	STOG_QUERY_QQ_VIP_INFO = 9000,
	GTOS_QUERY_QQ_VIP_INFO,
	STOG_QUERY_QQ_APP_FRIENDS,
	GTOS_QUERY_QQ_APP_FRIENDS,
	GTOG_QUERY_QQ_IS_LOGIN,

	MSG_END_CODE,
};

#endif
