// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "entity/test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* nesttest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  nesttest_reflection_ = NULL;
const ::google::protobuf::Descriptor* test_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  test_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_entity_2ftest_2eproto() {
  protobuf_AddDesc_entity_2ftest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "entity/test.proto");
  GOOGLE_CHECK(file != NULL);
  nesttest_descriptor_ = file->message_type(0);
  static const int nesttest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(nesttest, guid_),
  };
  nesttest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      nesttest_descriptor_,
      nesttest::default_instance_,
      nesttest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(nesttest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(nesttest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(nesttest));
  test_descriptor_ = file->message_type(1);
  static const int test_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, guid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, t_int32_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, t_uint32_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, t_string_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, t_uint32_rep_),
  };
  test_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      test_descriptor_,
      test::default_instance_,
      test_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(test, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(test));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_entity_2ftest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    nesttest_descriptor_, &nesttest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    test_descriptor_, &test::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_entity_2ftest_2eproto() {
  delete nesttest::default_instance_;
  delete nesttest_reflection_;
  delete test::default_instance_;
  delete test_reflection_;
}

void protobuf_AddDesc_entity_2ftest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021entity/test.proto\"\030\n\010nesttest\022\014\n\004guid\030"
    "\001 \002(\004\"_\n\004test\022\014\n\004guid\030\001 \002(\004\022\017\n\007t_int32\030\003"
    " \001(\005\022\020\n\010t_uint32\030\004 \001(\r\022\020\n\010t_string\030\007 \001(\t"
    "\022\024\n\014t_uint32_rep\030\010 \003(\r", 142);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "entity/test.proto", &protobuf_RegisterTypes);
  nesttest::default_instance_ = new nesttest();
  test::default_instance_ = new test();
  nesttest::default_instance_->InitAsDefaultInstance();
  test::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_entity_2ftest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_entity_2ftest_2eproto {
  StaticDescriptorInitializer_entity_2ftest_2eproto() {
    protobuf_AddDesc_entity_2ftest_2eproto();
  }
} static_descriptor_initializer_entity_2ftest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int nesttest::kGuidFieldNumber;
#endif  // !_MSC_VER

nesttest::nesttest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nesttest)
}

void nesttest::InitAsDefaultInstance() {
}

nesttest::nesttest(const nesttest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nesttest)
}

void nesttest::SharedCtor() {
  _cached_size_ = 0;
  guid_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

nesttest::~nesttest() {
  // @@protoc_insertion_point(destructor:nesttest)
  SharedDtor();
}

void nesttest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void nesttest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* nesttest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return nesttest_descriptor_;
}

const nesttest& nesttest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_entity_2ftest_2eproto();
  return *default_instance_;
}

nesttest* nesttest::default_instance_ = NULL;

nesttest* nesttest::New() const {
  return new nesttest;
}

void nesttest::Clear() {
  guid_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool nesttest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nesttest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 guid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &guid_)));
          set_has_guid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nesttest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nesttest)
  return false;
#undef DO_
}

void nesttest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nesttest)
  // required uint64 guid = 1;
  if (has_guid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->guid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nesttest)
}

::google::protobuf::uint8* nesttest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nesttest)
  // required uint64 guid = 1;
  if (has_guid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->guid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nesttest)
  return target;
}

int nesttest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 guid = 1;
    if (has_guid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->guid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void nesttest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const nesttest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const nesttest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void nesttest::MergeFrom(const nesttest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_guid()) {
      set_guid(from.guid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void nesttest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void nesttest::CopyFrom(const nesttest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool nesttest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void nesttest::Swap(nesttest* other) {
  if (other != this) {
    std::swap(guid_, other->guid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata nesttest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = nesttest_descriptor_;
  metadata.reflection = nesttest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int test::kGuidFieldNumber;
const int test::kTInt32FieldNumber;
const int test::kTUint32FieldNumber;
const int test::kTStringFieldNumber;
const int test::kTUint32RepFieldNumber;
#endif  // !_MSC_VER

test::test()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:test)
}

void test::InitAsDefaultInstance() {
}

test::test(const test& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:test)
}

void test::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  guid_ = GOOGLE_ULONGLONG(0);
  t_int32_ = 0;
  t_uint32_ = 0u;
  t_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

test::~test() {
  // @@protoc_insertion_point(destructor:test)
  SharedDtor();
}

void test::SharedDtor() {
  if (t_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete t_string_;
  }
  if (this != default_instance_) {
  }
}

void test::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* test::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return test_descriptor_;
}

const test& test::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_entity_2ftest_2eproto();
  return *default_instance_;
}

test* test::default_instance_ = NULL;

test* test::New() const {
  return new test;
}

void test::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<test*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(guid_, t_uint32_);
    if (has_t_string()) {
      if (t_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        t_string_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  t_uint32_rep_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool test::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 guid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &guid_)));
          set_has_guid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_t_int32;
        break;
      }

      // optional int32 t_int32 = 3;
      case 3: {
        if (tag == 24) {
         parse_t_int32:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &t_int32_)));
          set_has_t_int32();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_t_uint32;
        break;
      }

      // optional uint32 t_uint32 = 4;
      case 4: {
        if (tag == 32) {
         parse_t_uint32:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &t_uint32_)));
          set_has_t_uint32();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_t_string;
        break;
      }

      // optional string t_string = 7;
      case 7: {
        if (tag == 58) {
         parse_t_string:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_t_string()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->t_string().data(), this->t_string().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "t_string");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_t_uint32_rep;
        break;
      }

      // repeated uint32 t_uint32_rep = 8;
      case 8: {
        if (tag == 64) {
         parse_t_uint32_rep:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 64, input, this->mutable_t_uint32_rep())));
        } else if (tag == 66) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_t_uint32_rep())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_t_uint32_rep;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test)
  return false;
#undef DO_
}

void test::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test)
  // required uint64 guid = 1;
  if (has_guid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->guid(), output);
  }

  // optional int32 t_int32 = 3;
  if (has_t_int32()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->t_int32(), output);
  }

  // optional uint32 t_uint32 = 4;
  if (has_t_uint32()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->t_uint32(), output);
  }

  // optional string t_string = 7;
  if (has_t_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->t_string().data(), this->t_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "t_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->t_string(), output);
  }

  // repeated uint32 t_uint32_rep = 8;
  for (int i = 0; i < this->t_uint32_rep_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      8, this->t_uint32_rep(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:test)
}

::google::protobuf::uint8* test::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:test)
  // required uint64 guid = 1;
  if (has_guid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->guid(), target);
  }

  // optional int32 t_int32 = 3;
  if (has_t_int32()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->t_int32(), target);
  }

  // optional uint32 t_uint32 = 4;
  if (has_t_uint32()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->t_uint32(), target);
  }

  // optional string t_string = 7;
  if (has_t_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->t_string().data(), this->t_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "t_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->t_string(), target);
  }

  // repeated uint32 t_uint32_rep = 8;
  for (int i = 0; i < this->t_uint32_rep_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(8, this->t_uint32_rep(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test)
  return target;
}

int test::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 guid = 1;
    if (has_guid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->guid());
    }

    // optional int32 t_int32 = 3;
    if (has_t_int32()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->t_int32());
    }

    // optional uint32 t_uint32 = 4;
    if (has_t_uint32()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->t_uint32());
    }

    // optional string t_string = 7;
    if (has_t_string()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->t_string());
    }

  }
  // repeated uint32 t_uint32_rep = 8;
  {
    int data_size = 0;
    for (int i = 0; i < this->t_uint32_rep_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->t_uint32_rep(i));
    }
    total_size += 1 * this->t_uint32_rep_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void test::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const test* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const test*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void test::MergeFrom(const test& from) {
  GOOGLE_CHECK_NE(&from, this);
  t_uint32_rep_.MergeFrom(from.t_uint32_rep_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_guid()) {
      set_guid(from.guid());
    }
    if (from.has_t_int32()) {
      set_t_int32(from.t_int32());
    }
    if (from.has_t_uint32()) {
      set_t_uint32(from.t_uint32());
    }
    if (from.has_t_string()) {
      set_t_string(from.t_string());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void test::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void test::CopyFrom(const test& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool test::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void test::Swap(test* other) {
  if (other != this) {
    std::swap(guid_, other->guid_);
    std::swap(t_int32_, other->t_int32_);
    std::swap(t_uint32_, other->t_uint32_);
    std::swap(t_string_, other->t_string_);
    t_uint32_rep_.Swap(&other->t_uint32_rep_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata test::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = test_descriptor_;
  metadata.reflection = test_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
