// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/test.proto

#ifndef PROTOBUF_entity_2ftest_2eproto__INCLUDED
#define PROTOBUF_entity_2ftest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_entity_2ftest_2eproto();
void protobuf_AssignDesc_entity_2ftest_2eproto();
void protobuf_ShutdownFile_entity_2ftest_2eproto();

class nesttest;
class test;

// ===================================================================

class nesttest : public ::google::protobuf::Message {
 public:
  nesttest();
  virtual ~nesttest();

  nesttest(const nesttest& from);

  inline nesttest& operator=(const nesttest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const nesttest& default_instance();

  void Swap(nesttest* other);

  // implements Message ----------------------------------------------

  nesttest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const nesttest& from);
  void MergeFrom(const nesttest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::uint64 guid() const;
  inline void set_guid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:nesttest)
 private:
  inline void set_has_guid();
  inline void clear_has_guid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 guid_;
  friend void  protobuf_AddDesc_entity_2ftest_2eproto();
  friend void protobuf_AssignDesc_entity_2ftest_2eproto();
  friend void protobuf_ShutdownFile_entity_2ftest_2eproto();

  void InitAsDefaultInstance();
  static nesttest* default_instance_;
};
// -------------------------------------------------------------------

class test : public ::google::protobuf::Message {
 public:
  test();
  virtual ~test();

  test(const test& from);

  inline test& operator=(const test& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const test& default_instance();

  void Swap(test* other);

  // implements Message ----------------------------------------------

  test* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const test& from);
  void MergeFrom(const test& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::uint64 guid() const;
  inline void set_guid(::google::protobuf::uint64 value);

  // optional int32 t_int32 = 3;
  inline bool has_t_int32() const;
  inline void clear_t_int32();
  static const int kTInt32FieldNumber = 3;
  inline ::google::protobuf::int32 t_int32() const;
  inline void set_t_int32(::google::protobuf::int32 value);

  // optional uint32 t_uint32 = 4;
  inline bool has_t_uint32() const;
  inline void clear_t_uint32();
  static const int kTUint32FieldNumber = 4;
  inline ::google::protobuf::uint32 t_uint32() const;
  inline void set_t_uint32(::google::protobuf::uint32 value);

  // optional string t_string = 7;
  inline bool has_t_string() const;
  inline void clear_t_string();
  static const int kTStringFieldNumber = 7;
  inline const ::std::string& t_string() const;
  inline void set_t_string(const ::std::string& value);
  inline void set_t_string(const char* value);
  inline void set_t_string(const char* value, size_t size);
  inline ::std::string* mutable_t_string();
  inline ::std::string* release_t_string();
  inline void set_allocated_t_string(::std::string* t_string);

  // repeated uint32 t_uint32_rep = 8;
  inline int t_uint32_rep_size() const;
  inline void clear_t_uint32_rep();
  static const int kTUint32RepFieldNumber = 8;
  inline ::google::protobuf::uint32 t_uint32_rep(int index) const;
  inline void set_t_uint32_rep(int index, ::google::protobuf::uint32 value);
  inline void add_t_uint32_rep(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      t_uint32_rep() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_t_uint32_rep();

  // @@protoc_insertion_point(class_scope:test)
 private:
  inline void set_has_guid();
  inline void clear_has_guid();
  inline void set_has_t_int32();
  inline void clear_has_t_int32();
  inline void set_has_t_uint32();
  inline void clear_has_t_uint32();
  inline void set_has_t_string();
  inline void clear_has_t_string();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 guid_;
  ::google::protobuf::int32 t_int32_;
  ::google::protobuf::uint32 t_uint32_;
  ::std::string* t_string_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > t_uint32_rep_;
  friend void  protobuf_AddDesc_entity_2ftest_2eproto();
  friend void protobuf_AssignDesc_entity_2ftest_2eproto();
  friend void protobuf_ShutdownFile_entity_2ftest_2eproto();

  void InitAsDefaultInstance();
  static test* default_instance_;
};
// ===================================================================


// ===================================================================

// nesttest

// required uint64 guid = 1;
inline bool nesttest::has_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void nesttest::set_has_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void nesttest::clear_has_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void nesttest::clear_guid() {
  guid_ = GOOGLE_ULONGLONG(0);
  clear_has_guid();
}
inline ::google::protobuf::uint64 nesttest::guid() const {
  // @@protoc_insertion_point(field_get:nesttest.guid)
  return guid_;
}
inline void nesttest::set_guid(::google::protobuf::uint64 value) {
  set_has_guid();
  guid_ = value;
  // @@protoc_insertion_point(field_set:nesttest.guid)
}

// -------------------------------------------------------------------

// test

// required uint64 guid = 1;
inline bool test::has_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void test::set_has_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void test::clear_has_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void test::clear_guid() {
  guid_ = GOOGLE_ULONGLONG(0);
  clear_has_guid();
}
inline ::google::protobuf::uint64 test::guid() const {
  // @@protoc_insertion_point(field_get:test.guid)
  return guid_;
}
inline void test::set_guid(::google::protobuf::uint64 value) {
  set_has_guid();
  guid_ = value;
  // @@protoc_insertion_point(field_set:test.guid)
}

// optional int32 t_int32 = 3;
inline bool test::has_t_int32() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void test::set_has_t_int32() {
  _has_bits_[0] |= 0x00000002u;
}
inline void test::clear_has_t_int32() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void test::clear_t_int32() {
  t_int32_ = 0;
  clear_has_t_int32();
}
inline ::google::protobuf::int32 test::t_int32() const {
  // @@protoc_insertion_point(field_get:test.t_int32)
  return t_int32_;
}
inline void test::set_t_int32(::google::protobuf::int32 value) {
  set_has_t_int32();
  t_int32_ = value;
  // @@protoc_insertion_point(field_set:test.t_int32)
}

// optional uint32 t_uint32 = 4;
inline bool test::has_t_uint32() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void test::set_has_t_uint32() {
  _has_bits_[0] |= 0x00000004u;
}
inline void test::clear_has_t_uint32() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void test::clear_t_uint32() {
  t_uint32_ = 0u;
  clear_has_t_uint32();
}
inline ::google::protobuf::uint32 test::t_uint32() const {
  // @@protoc_insertion_point(field_get:test.t_uint32)
  return t_uint32_;
}
inline void test::set_t_uint32(::google::protobuf::uint32 value) {
  set_has_t_uint32();
  t_uint32_ = value;
  // @@protoc_insertion_point(field_set:test.t_uint32)
}

// optional string t_string = 7;
inline bool test::has_t_string() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void test::set_has_t_string() {
  _has_bits_[0] |= 0x00000008u;
}
inline void test::clear_has_t_string() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void test::clear_t_string() {
  if (t_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    t_string_->clear();
  }
  clear_has_t_string();
}
inline const ::std::string& test::t_string() const {
  // @@protoc_insertion_point(field_get:test.t_string)
  return *t_string_;
}
inline void test::set_t_string(const ::std::string& value) {
  set_has_t_string();
  if (t_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    t_string_ = new ::std::string;
  }
  t_string_->assign(value);
  // @@protoc_insertion_point(field_set:test.t_string)
}
inline void test::set_t_string(const char* value) {
  set_has_t_string();
  if (t_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    t_string_ = new ::std::string;
  }
  t_string_->assign(value);
  // @@protoc_insertion_point(field_set_char:test.t_string)
}
inline void test::set_t_string(const char* value, size_t size) {
  set_has_t_string();
  if (t_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    t_string_ = new ::std::string;
  }
  t_string_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test.t_string)
}
inline ::std::string* test::mutable_t_string() {
  set_has_t_string();
  if (t_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    t_string_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test.t_string)
  return t_string_;
}
inline ::std::string* test::release_t_string() {
  clear_has_t_string();
  if (t_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = t_string_;
    t_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void test::set_allocated_t_string(::std::string* t_string) {
  if (t_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete t_string_;
  }
  if (t_string) {
    set_has_t_string();
    t_string_ = t_string;
  } else {
    clear_has_t_string();
    t_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test.t_string)
}

// repeated uint32 t_uint32_rep = 8;
inline int test::t_uint32_rep_size() const {
  return t_uint32_rep_.size();
}
inline void test::clear_t_uint32_rep() {
  t_uint32_rep_.Clear();
}
inline ::google::protobuf::uint32 test::t_uint32_rep(int index) const {
  // @@protoc_insertion_point(field_get:test.t_uint32_rep)
  return t_uint32_rep_.Get(index);
}
inline void test::set_t_uint32_rep(int index, ::google::protobuf::uint32 value) {
  t_uint32_rep_.Set(index, value);
  // @@protoc_insertion_point(field_set:test.t_uint32_rep)
}
inline void test::add_t_uint32_rep(::google::protobuf::uint32 value) {
  t_uint32_rep_.Add(value);
  // @@protoc_insertion_point(field_add:test.t_uint32_rep)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
test::t_uint32_rep() const {
  // @@protoc_insertion_point(field_list:test.t_uint32_rep)
  return t_uint32_rep_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
test::mutable_t_uint32_rep() {
  // @@protoc_insertion_point(field_mutable_list:test.t_uint32_rep)
  return &t_uint32_rep_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_entity_2ftest_2eproto__INCLUDED
